import { ArrowRight, CalendarDays, Map, Sparkles, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { brandColor, brandName, type Tenant } from '../lib/tenantCore'

export type LandingTemplate = 'summit' | 'expo' | 'minimal'
export type LandingConfig = { template?: LandingTemplate; eyebrow?: string; headline?: string; subheadline?: string; cta_label?: string; hero_image_url?: string; show_agenda?: boolean; show_exhibition?: boolean; show_interest?: boolean }
export type LandingEvent = { id: string; name: string; description: string | null; event_type: string; start_date: string | null; config: Record<string, unknown> | null }
const defaults: Required<Omit<LandingConfig, 'hero_image_url'>> = { template: 'summit', eyebrow: 'Próximamente', headline: '', subheadline: '', cta_label: 'Registrarme', show_agenda: true, show_exhibition: true, show_interest: true }
function copy(event: LandingEvent) { const c = (event.config?.public_landing ?? {}) as LandingConfig; return { ...defaults, ...c, headline: c.headline?.trim() || event.name, subheadline: c.subheadline?.trim() || event.description || 'Una experiencia creada para conectar personas, conocimiento y oportunidades.' } }

export default function EventPublicLanding({ event, tenant }: { event: LandingEvent; tenant: Tenant }) {
  const content = copy(event); const accent = brandColor(tenant) ?? '#047857'; const name = brandName(tenant); const date = event.start_date ? new Date(event.start_date).toLocaleDateString('es-VE', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Fecha por confirmar'
  const dark = content.template === 'summit'; const expo = content.template === 'expo'
  return <div className={dark ? 'min-h-[100dvh] bg-zinc-950 text-white' : 'min-h-[100dvh] bg-zinc-50 text-zinc-950'}>
    <header className={`relative z-10 border-b ${dark ? 'border-white/10 bg-zinc-950/80 text-white' : 'border-zinc-200 bg-white/90'} backdrop-blur`}><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-7"><span className="font-semibold tracking-tight">{name}</span><Link to={`/e/${event.id}`} className={`rounded-full px-3 py-2 text-sm font-semibold ${dark ? 'bg-white text-zinc-950' : 'text-white'}`} style={dark ? undefined : { backgroundColor: accent }}>{content.cta_label}</Link></div></header>
    <main><section className={`relative isolate overflow-hidden ${dark ? 'bg-zinc-950' : expo ? 'bg-emerald-50' : 'bg-white'}`}><div className="absolute inset-0 -z-10">{content.hero_image_url ? <img src={content.hero_image_url} alt="" className="h-full w-full object-cover"/> : <div className={dark ? 'h-full bg-[radial-gradient(circle_at_80%_10%,#0f766e,transparent_35%),linear-gradient(135deg,#09090b,#14211f)]' : expo ? 'h-full bg-[radial-gradient(circle_at_85%_15%,#bbf7d0,transparent_35%),linear-gradient(135deg,#ecfdf5,#ffffff)]' : 'h-full bg-[radial-gradient(circle_at_90%_20%,#d1fae5,transparent_30%),#fff]'} />}{content.hero_image_url && <div className={dark ? 'absolute inset-0 bg-zinc-950/70' : 'absolute inset-0 bg-white/65'} />}</div><div className="mx-auto grid min-h-[min(680px,100dvh)] max-w-7xl items-center gap-10 px-4 py-20 sm:px-7 lg:grid-cols-[1.15fr_.85fr]"><div className="max-w-3xl"><p className="font-semibold" style={{ color: dark ? '#6ee7b7' : accent }}>{content.eyebrow}</p><h1 className="mt-5 text-4xl font-bold leading-[1.04] tracking-[-.04em] sm:text-6xl">{content.headline}</h1><p className={`mt-6 max-w-xl text-lg leading-8 ${dark ? 'text-zinc-300' : 'text-zinc-600'}`}>{content.subheadline}</p><div className="mt-8 flex flex-wrap gap-3"><Link to={`/e/${event.id}`} className="inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm font-bold text-white" style={{ backgroundColor: accent }}>{content.cta_label}<ArrowRight className="h-4 w-4"/></Link>{content.show_interest && <Link to={`/e/${event.id}/interes/solicita-informacion`} className={`inline-flex items-center gap-2 rounded-full border px-5 py-3 text-sm font-bold ${dark ? 'border-white/25 text-white' : 'border-zinc-300 text-zinc-800'}`}>Solicitar información</Link>}</div></div><aside className={`rounded-3xl border p-6 ${dark ? 'border-white/15 bg-white/10 backdrop-blur' : 'border-white/70 bg-white/80 shadow-xl shadow-emerald-950/5'}`}><p className="text-sm font-semibold" style={{ color: dark ? '#a7f3d0' : accent }}>{date}</p><p className="mt-4 text-2xl font-bold">Una experiencia para participar, descubrir y conectar.</p><div className={`mt-6 grid gap-3 text-sm ${dark ? 'text-zinc-200' : 'text-zinc-600'}`}><span className="flex items-center gap-3"><CalendarDays className="h-5 w-5" style={{ color: accent }}/>Agenda y contenido</span><span className="flex items-center gap-3"><Users className="h-5 w-5" style={{ color: accent }}/>Oportunidades para asistentes y aliados</span>{event.event_type === 'exhibition' && <span className="flex items-center gap-3"><Map className="h-5 w-5" style={{ color: accent }}/>Expositores y plano interactivo</span>}</div></aside></div></section>
    <section className={dark ? 'bg-zinc-900 py-16 sm:py-24' : 'py-16 sm:py-24'}><div className="mx-auto max-w-7xl px-4 sm:px-7"><h2 className="max-w-2xl text-3xl font-bold tracking-tight sm:text-5xl">Todo lo esencial, en un mismo recorrido.</h2><div className="mt-10 grid gap-4 md:grid-cols-3"><article className={`rounded-2xl p-6 ${dark ? 'bg-white/5' : 'bg-emerald-50'}`}><CalendarDays className="h-6 w-6" style={{ color: accent }}/><h3 className="mt-8 text-xl font-bold">Programa claro</h3><p className={`mt-2 text-sm leading-6 ${dark ? 'text-zinc-300' : 'text-zinc-600'}`}>Consulta sesiones, horarios y actividades relevantes.</p>{content.show_agenda && <Link to={`/e/${event.id}/agenda`} className="mt-5 inline-flex text-sm font-bold" style={{ color: accent }}>Ver agenda</Link>}</article><article className={`rounded-2xl p-6 ${dark ? 'bg-white/5' : 'bg-zinc-100'}`}><Sparkles className="h-6 w-6" style={{ color: accent }}/><h3 className="mt-8 text-xl font-bold">Registro simple</h3><p className={`mt-2 text-sm leading-6 ${dark ? 'text-zinc-300' : 'text-zinc-600'}`}>Asegura tu participación desde cualquier dispositivo.</p><Link to={`/e/${event.id}`} className="mt-5 inline-flex text-sm font-bold" style={{ color: accent }}>Abrir registro</Link></article>{event.event_type === 'exhibition' && content.show_exhibition ? <article className={`rounded-2xl p-6 ${dark ? 'bg-white/5' : 'bg-emerald-50'}`}><Map className="h-6 w-6" style={{ color: accent }}/><h3 className="mt-8 text-xl font-bold">Exposición</h3><p className={`mt-2 text-sm leading-6 ${dark ? 'text-zinc-300' : 'text-zinc-600'}`}>Explora empresas y ubícalas en el plano.</p><Link to={`/expo/${event.id}/plano`} className="mt-5 inline-flex text-sm font-bold" style={{ color: accent }}>Ver plano</Link></article> : <article className={`rounded-2xl p-6 ${dark ? 'bg-white/5' : 'bg-zinc-100'}`}><Users className="h-6 w-6" style={{ color: accent }}/><h3 className="mt-8 text-xl font-bold">Conexiones reales</h3><p className={`mt-2 text-sm leading-6 ${dark ? 'text-zinc-300' : 'text-zinc-600'}`}>Encuentra contenidos, aliados y oportunidades.</p></article>}</div></div></section></main>
    <footer className={dark ? 'border-t border-white/10 bg-zinc-950 px-4 py-8 text-sm text-zinc-400 sm:px-7' : 'border-t bg-white px-4 py-8 text-sm text-zinc-500 sm:px-7'}><div className="mx-auto max-w-7xl">{name} · {event.name}</div></footer>
  </div>
}
