import { useMemo, useState } from 'react'
import { Eye, ImagePlus, Plus, Printer, Save, Square, Type, X } from 'lucide-react'
import { Layer, Rect, Stage, Text } from 'react-konva'
import { BADGE_FIELD_LABELS, defaultBadgeLayout, normalizeBadgeLayout, renderBadgeSides, type BadgeElement, type BadgeField, type BadgeRenderData, type BadgeTemplateV2 } from '../../lib/badgeStudio'

const input='w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm'
const sample:Record<BadgeField,string>={full_name:'María Rodríguez',first_name:'María',last_name:'Rodríguez',company:'Energía de Venezuela',job_title:'Directora de Operaciones',identification:'V-12.345.678',participation_type:'VIP',event_name:'Expo Venezuela Energética 2026',organization_name:'EventosFácil',seat:'Asiento A-12',qr:'▦ QR'}

export default function BadgeStudio({template,onChange,onSave,busy,previewData,onTestPrint,testBusy=false}:{template:BadgeTemplateV2;onChange:(value:BadgeTemplateV2)=>void;onSave:()=>void;busy:boolean;previewData?:BadgeRenderData;onTestPrint?:()=>void;testBusy?:boolean}){
  const [selected,setSelected]=useState<string|null>(null)
  const [side,setSide]=useState<'front'|'back'>('front')
  const [preview,setPreview]=useState<string[]|null>(null)
  const width=Number(template.width_mm)||100,height=Number(template.height_mm)||60
  const scale=Math.min(5,760/width,470/height)
  const layout=side==='front'?normalizeBadgeLayout(template):template.back_layout
  const elements=layout.elements
  const selectedElement=elements.find(item=>item.id===selected)
  const updateLayout=(next:BadgeElement[])=>onChange({...template,[side==='front'?'layout':'back_layout']:{version:1,elements:next}})
  const updateElement=(values:Partial<BadgeElement>)=>selected&&updateLayout(elements.map(item=>item.id===selected?{...item,...values}:item))
  const add=(element:Omit<BadgeElement,'id'>)=>{const value={...element,id:crypto.randomUUID()};updateLayout([...elements,value]);setSelected(value.id)}
  const reset=()=>{const value=defaultBadgeLayout(width,height,template.primary_color);onChange({...template,[side==='front'?'layout':'back_layout']:value});setSelected(null)}
  const canvasStyle=useMemo(()=>({width:width*scale,height:height*scale}),[width,height,scale])
  const openPreview=async()=>{if(previewData)setPreview(await renderBadgeSides(template,previewData))}
  return <section className="mt-5 rounded-2xl border border-violet-200 bg-violet-50/60 p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Badge Studio</h2><p className="mt-1 text-sm text-zinc-600">Arrastra los elementos sobre la credencial y configura sus dimensiones en milímetros.</p></div><div className="flex flex-wrap gap-2">{template.double_sided&&<button type="button" onClick={()=>setSide(value=>value==='front'?'back':'front')} className="rounded-lg border bg-white px-3 py-2 text-sm font-semibold">{side==='front'?'Editar reverso':'Editar frente'}</button>}<button type="button" onClick={()=>void openPreview()} disabled={!previewData} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-semibold disabled:opacity-40"><Eye className="h-4 w-4"/>Vista previa real</button>{onTestPrint&&<button type="button" onClick={onTestPrint} disabled={!previewData||testBusy} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-semibold disabled:opacity-40"><Printer className="h-4 w-4"/>{testBusy?'Imprimiendo…':'Prueba sin auditoría'}</button>}<button type="button" onClick={onSave} disabled={busy} className="inline-flex items-center gap-2 rounded-lg bg-violet-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4"/>Guardar y publicar</button></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[230px_minmax(0,1fr)_260px]">
      <aside className="space-y-4 rounded-xl border bg-white p-4">
        <label className="grid gap-1 text-xs font-semibold">Nombre de plantilla<input className={input} value={template.name} onChange={e=>onChange({...template,name:e.target.value})}/></label>
        <div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-xs font-semibold">Ancho mm<input className={input} type="number" min="20" max="400" value={width} onChange={e=>onChange({...template,width_mm:Number(e.target.value)})}/></label><label className="grid gap-1 text-xs font-semibold">Alto mm<input className={input} type="number" min="20" max="400" value={height} onChange={e=>onChange({...template,height_mm:Number(e.target.value)})}/></label></div>
        <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={template.double_sided} onChange={e=>onChange({...template,double_sided:e.target.checked})}/>Doble cara</label>
        <div><p className="text-xs font-bold uppercase text-zinc-500">Campos dinámicos</p><div className="mt-2 grid gap-1">{Object.entries(BADGE_FIELD_LABELS).map(([field,label])=><button key={field} type="button" onClick={()=>add({kind:'field',field:field as BadgeField,x:5,y:5,width:field==='qr'?22:55,height:field==='qr'?22:8,fontSize:4,fontWeight:field==='full_name'?'bold':'normal',color:template.text_color,align:'left'})} className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-left text-xs hover:bg-violet-50"><Plus className="h-3 w-3"/>{label}</button>)}</div></div>
        <div className="grid gap-2"><button type="button" onClick={()=>add({kind:'text',text:'Texto personalizado',x:5,y:5,width:50,height:8,fontSize:4,color:template.text_color})} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold"><Type className="h-4 w-4"/>Añadir texto</button><button type="button" onClick={()=>add({kind:'rect',x:5,y:5,width:30,height:8,backgroundColor:template.primary_color,radius:1})} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold"><Square className="h-4 w-4"/>Añadir forma</button><button type="button" onClick={()=>add({kind:'image',src:'',x:5,y:5,width:25,height:15})} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold"><ImagePlus className="h-4 w-4"/>Añadir imagen</button><button type="button" onClick={reset} className="rounded-lg px-3 py-2 text-xs font-semibold text-violet-700">Restaurar diseño recomendado</button></div>
      </aside>
      <div className="overflow-auto rounded-xl border bg-zinc-200 p-5"><div className="mx-auto overflow-hidden bg-white shadow-xl" style={canvasStyle}><Stage width={width*scale} height={height*scale} onMouseDown={event=>{if(event.target===event.target.getStage())setSelected(null)}}><Layer><Rect width={width*scale} height={height*scale} fill={template.background_color}/>{elements.map(element=>{
        const common={x:element.x*scale,y:element.y*scale,width:element.width*scale,height:element.height*scale,rotation:element.rotation??0,draggable:true,onClick:()=>setSelected(element.id),onTap:()=>setSelected(element.id)}
        const onDragEnd=(event:{target:{x:()=>number;y:()=>number}})=>{const x=Math.max(0,event.target.x()/scale),y=Math.max(0,event.target.y()/scale);updateLayout(elements.map(item=>item.id===element.id?{...item,x,y}:item))}
        if(element.kind==='rect')return <Rect key={element.id} {...common} onDragEnd={onDragEnd} fill={element.backgroundColor||template.primary_color} cornerRadius={(element.radius??0)*scale} stroke={selected===element.id?'#7c3aed':undefined} strokeWidth={selected===element.id?2:0}/>
        const text=element.kind==='image'?(element.src?'IMAGEN':'Selecciona una imagen'):element.kind==='text'?(element.text??'Texto'):sample[element.field??'full_name']
        return <Text key={element.id} {...common} onDragEnd={onDragEnd} text={text} fontFamily="Arial" fontSize={(element.fontSize??3.5)*scale} fontStyle={element.fontWeight==='bold'?'bold':'normal'} fill={element.color||template.text_color} align={element.align??'left'} verticalAlign="middle" padding={1.5*scale} stroke={selected===element.id?'#7c3aed':undefined} strokeWidth={selected===element.id ? 0.3 : 0}/>
      })}</Layer></Stage></div><p className="mt-4 text-center text-xs text-zinc-600">Vista {side==='front'?'frontal':'posterior'} · {width} × {height} mm · {template.dpi} DPI</p></div>
      <aside className="rounded-xl border bg-white p-4">{selectedElement?<><div className="flex items-center justify-between"><h3 className="font-semibold">Elemento</h3><button type="button" onClick={()=>{updateLayout(elements.filter(item=>item.id!==selected));setSelected(null)}} className="text-xs font-semibold text-red-700">Eliminar</button></div><div className="mt-3 grid grid-cols-2 gap-2">{(['x','y','width','height'] as const).map(key=><label key={key} className="grid gap-1 text-xs font-semibold">{key.toUpperCase()} mm<input className={input} type="number" step="0.5" value={selectedElement[key]} onChange={e=>updateElement({[key]:Number(e.target.value)})}/></label>)}</div>{selectedElement.kind==='text'&&<label className="mt-3 grid gap-1 text-xs font-semibold">Texto<input className={input} value={selectedElement.text??''} onChange={e=>updateElement({text:e.target.value})}/></label>}{selectedElement.kind==='image'&&<label className="mt-3 grid gap-1 text-xs font-semibold">URL de imagen<input className={input} value={selectedElement.src??''} onChange={e=>updateElement({src:e.target.value})}/></label>}{selectedElement.kind!=='image'&&selectedElement.kind!=='rect'&&<><label className="mt-3 grid gap-1 text-xs font-semibold">Tamaño de texto<input className={input} type="number" min="1.5" max="30" step="0.5" value={selectedElement.fontSize??3.5} onChange={e=>updateElement({fontSize:Number(e.target.value)})}/></label><label className="mt-3 grid gap-1 text-xs font-semibold">Alineación<select className={input} value={selectedElement.align??'left'} onChange={e=>updateElement({align:e.target.value as BadgeElement['align']})}><option value="left">Izquierda</option><option value="center">Centro</option><option value="right">Derecha</option></select></label><label className="mt-3 grid gap-1 text-xs font-semibold">Color<input className={input} type="color" value={selectedElement.color??template.text_color} onChange={e=>updateElement({color:e.target.value})}/></label></>}<label className="mt-3 grid gap-1 text-xs font-semibold">Rotación<input className={input} type="number" min="-180" max="180" value={selectedElement.rotation??0} onChange={e=>updateElement({rotation:Number(e.target.value)})}/></label></>:<p className="text-sm text-zinc-500">Selecciona un elemento del lienzo para ajustar su posición, tamaño y estilo.</p>}</aside>
    </div>
    {preview&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-5" role="dialog" aria-modal="true" aria-label="Vista previa de credencial"><div className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">Vista previa con datos reales</h3><p className="text-sm text-zinc-500">{preview.length===2?'Frente y reverso':'Frente'} a {template.dpi} DPI</p></div><button type="button" onClick={()=>setPreview(null)} className="rounded-lg border p-2" aria-label="Cerrar"><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-5 md:grid-cols-2">{preview.map((url,index)=><figure key={url} className="rounded-xl bg-zinc-100 p-4"><img src={url} alt={index===0?'Frente de la credencial':'Reverso de la credencial'} className="mx-auto max-h-[58vh] w-auto shadow-xl"/><figcaption className="mt-3 text-center text-sm font-semibold">{index===0?'Frente':'Reverso'}</figcaption></figure>)}</div></div></div>}
  </section>
}
