import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Code2, Download, Heart, MapPin, Navigation, Search, Share2, Star, X } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { supabase } from '../lib/supabase'
import PublicExhibitionCanvas from './PublicExhibitionCanvas'
import type { SceneElement } from './admin/exhibition/ExhibitionKonvaStage'

type MapRow = { id: string; name: string; event_id: string; organization_id: string; published: boolean; metadata: Record<string, unknown> | null }
type Branding = { name?: string | null; logo_url?: string | null; color?: string | null }
type RawElement = { id: string; label: string; element_type: string; status: string; x: number; y: number; width: number; height: number; geometry?: Record<string, unknown> | null; price?: number | null; currency?: string | null; booth_type?: string | null; tags?: string[]; metadata?: Record<string, unknown> | null; style?: Record<string, unknown> | null; layer?: string | null; z_index?: number | null; locked?: boolean | null; visible?: boolean | null }
type PublicRoute = { id: string; name: string; kind: string; geometry: unknown; active: boolean }
type PublicSession = { session_id: string; session_name: string; session_description: string | null; starts_at: string | null; ends_at: string | null; stage_name: string | null; venue_element_id: string | null; speakers: Array<{ full_name: string; company: string | null; position: string | null }> }
const sessionKey = () => { const key = 'floorplan-session'; const existing = localStorage.getItem(key); if (existing) return existing; const value = crypto.randomUUID(); localStorage.setItem(key, value); return value }
const metadataText = (item: SceneElement, key: string) => { const value = item.metadata?.[key]; return typeof value === 'string' ? value : '' }
const normalize = (raw: RawElement, companyName?: string): SceneElement => { const metadata = { ...(raw.metadata ?? {}), ...(companyName ? { company_name: companyName } : {}) }; const geometry = raw.geometry && typeof raw.geometry === 'object' ? raw.geometry : {}; return { ...raw, metadata, geometry: { x: Number(geometry.x ?? raw.x), y: Number(geometry.y ?? raw.y), width: Number(geometry.width ?? raw.width), height: Number(geometry.height ?? raw.height), rotation: Number(geometry.rotation ?? 0), shape: geometry.shape === 'polygon' ? 'polygon' : 'rect', points: Array.isArray(geometry.points) ? geometry.points as number[] : undefined }, layer: raw.layer ?? (raw.element_type === 'stand' ? 'layout' : 'architecture'), z_index: Number(raw.z_index ?? 1), locked: Boolean(raw.locked), visible: raw.visible !== false, style: raw.style ?? {} } as SceneElement }
const labelForType = (type: string) => ({ stand: 'Stand', aisle: 'Pasillo', access_point: 'Acceso', entrance: 'Entrada', exit: 'Salida', stage: 'Escenario', zone: 'Zona', restroom: 'Baños', information: 'Información', food: 'Alimentos', parking: 'Estacionamiento' }[type] ?? 'Punto de interés')
const score = (value: string, term: string) => { if (!term) return 1; const normalizeText = (text: string) => text.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g, ''); const normalized = normalizeText(value); const query = normalizeText(term); if (normalized.includes(query)) return 3; return query.split(/\s+/).every((word) => normalized.includes(word)) ? 1 : 0 }

export default function PlanoPublico() {
  const { eventId } = useParams<{ eventId: string }>(); const [params, setParams] = useSearchParams()
  const [map, setMap] = useState<MapRow | null>(null); const [elements, setElements] = useState<SceneElement[]>([]); const [assignments, setAssignments] = useState<Map<string, string>>(new Map()); const [branding, setBranding] = useState<Branding>({}); const [routes, setRoutes] = useState<PublicRoute[]>([]); const [sessions, setSessions] = useState<PublicSession[]>([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [favoritesOnly, setFavoritesOnly] = useState(false); const [selected, setSelected] = useState<SceneElement | null>(null); const [showEmbed, setShowEmbed] = useState(false); const [favorites, setFavorites] = useState<string[]>(() => JSON.parse(localStorage.getItem(`floorplan-favorites-${eventId}`) ?? '[]') as string[]); const [message, setMessage] = useState('Cargando plano…')
  const columns = Number(map?.metadata?.width_units ?? 40); const rows = Number(map?.metadata?.height_units ?? 24); const accent = branding.color ?? '#047857'; const title = branding.name ?? 'Plano de exposición'
  const categories = useMemo(() => [...new Set(elements.flatMap((item) => [...(item.tags ?? []), metadataText(item, 'category')]).filter((value): value is string => Boolean(value)))].sort((a, b) => a.localeCompare(b, 'es')), [elements])
  const filtered = useMemo(() => elements.filter((item) => { const text = [item.label, metadataText(item, 'company_name'), metadataText(item, 'purpose'), metadataText(item, 'description'), labelForType(item.element_type ?? ''), ...(item.tags ?? [])].filter((value): value is string => typeof value === 'string').join(' '); const matchesSearch = score(text, query) > 0; const matchesCategory = !category || (item.tags ?? []).includes(category) || metadataText(item, 'category') === category; const matchesFavorite = !favoritesOnly || favorites.includes(item.id); return matchesSearch && matchesCategory && matchesFavorite }), [elements, query, category, favoritesOnly, favorites])
  const stands = filtered.filter((item) => item.element_type === 'stand'); const selectedCompany = selected ? metadataText(selected, 'company_name') : ''
  useEffect(() => { if (!eventId) return; void load() }, [eventId])
  useEffect(() => { if (!eventId) return; void supabase.rpc('get_public_forum_agenda', { p_event_id: eventId }).then(({ data }) => setSessions((data ?? []) as PublicSession[])) }, [eventId])
  useEffect(() => { const id = params.get('element'); if (id) setSelected(elements.find((item) => item.id === id) ?? null) }, [elements, params])
  async function track(eventType: 'view' | 'search' | 'select' | 'favorite' | 'route' | 'qr_scan', elementId?: string, mapOverride?: MapRow) { const activeMap = mapOverride ?? map; if (!activeMap || !eventId) return; await supabase.from('floor_plan_analytics').insert({ organization_id: activeMap.organization_id, event_id: eventId, map_id: activeMap.id, map_element_id: elementId ?? null, event_type: eventType, session_id: sessionKey(), metadata: { query, category } }) }
  async function load() { const { data: maps, error } = await supabase.from('venue_maps').select('id,name,event_id,organization_id,published,metadata').eq('event_id', eventId).eq('published', true).order('published_at', { ascending: false, nullsFirst: false }).order('created_at', { ascending: false }).limit(1); const next = maps?.[0] as MapRow | undefined; if (error || !next) { setMessage(error?.message ?? 'El plano aún no está publicado.'); return }; const [elementResult, assignmentResult, orgResult, routeResult] = await Promise.all([supabase.from('venue_map_elements').select('id,label,element_type,status,x,y,width,height,geometry,price,currency,booth_type,tags,metadata,style,layer,z_index,locked,visible').eq('map_id', next.id).eq('public_visible', true).eq('visible', true).order('z_index'), supabase.from('published_exhibition_directory').select('element_id,company_name'), supabase.from('organizations').select('name,branding').eq('id', next.organization_id).maybeSingle(), supabase.from('floor_plan_routes').select('id,name,kind,geometry,active').eq('map_id', next.id).eq('active', true).order('name')]); setMap(next); setBranding((orgResult.data?.branding as Branding | null) ?? {}); setRoutes((routeResult.data ?? []) as PublicRoute[]); const rows = (elementResult.data ?? []) as RawElement[]; const ids = new Set(rows.filter((item) => item.element_type === 'stand').map((item) => item.id)); const nextAssignments = new Map<string, string>(); (assignmentResult.data ?? []).forEach((item) => { if (ids.has(item.element_id) && item.company_name) nextAssignments.set(item.element_id, [nextAssignments.get(item.element_id), item.company_name].filter(Boolean).join(' · ')) }); setAssignments(nextAssignments); setElements(rows.map((item) => normalize(item, nextAssignments.get(item.id)))); setMessage(elementResult.error?.message ?? ''); await track('view', undefined, next) }
  function choose(item: SceneElement | null) { setSelected(item); if (item) { setParams((current) => { current.set('element', item.id); return current }, { replace: true }); void track('select', item.id) } else setParams((current) => { current.delete('element'); return current }, { replace: true }) }
  function toggleFavorite(item: SceneElement) { const next = favorites.includes(item.id) ? favorites.filter((id) => id !== item.id) : [...favorites, item.id]; setFavorites(next); localStorage.setItem(`floorplan-favorites-${eventId}`, JSON.stringify(next)); void track('favorite', item.id) }
  async function shareSelected() { if (!selected) return; const url = `${window.location.origin}/expo/${eventId}/plano?element=${selected.id}`; if (navigator.share) await navigator.share({ title: selectedCompany || selected.label, text: `Ubicación de ${selectedCompany || selected.label}`, url }); else { await navigator.clipboard?.writeText(url); setMessage('Enlace del stand copiado.'); setTimeout(() => setMessage(''), 2500) } }
  function printPlan() { void track('view'); window.print() }
  const embedCode = `<iframe src="${window.location.origin}/expo/${eventId}/plano?embed=1" title="${title}" width="100%" height="720" style="border:0;border-radius:16px" loading="lazy"></iframe>`
  return (
    <main className="min-h-screen bg-slate-50 p-3 pb-24 text-slate-900 sm:p-6 lg:pb-8 print:bg-white print:p-0" style={{ ['--brand' as string]: accent }}>
      <div className="mx-auto max-w-7xl">
        <header className="mb-4 flex flex-wrap items-start justify-between gap-4 rounded-2xl border bg-white p-4 print:hidden sm:p-5">
          <div className="flex min-w-0 items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-50" style={{ color: accent }}>{branding.logo_url ? <img src={branding.logo_url} alt={title} className="h-10 w-10 rounded object-contain" /> : <MapPin className="h-6 w-6" />}</div><div className="min-w-0"><Link to={`/e/${eventId}`} className="text-sm text-slate-500">← Volver al evento</Link><p className="mt-1 truncate text-xs font-semibold uppercase tracking-wide" style={{ color: accent }}>{title}</p><h1 className="mt-1 text-xl font-bold sm:text-2xl">Plano y directorio de expositores</h1><p className="mt-1 text-sm text-slate-600">Busca empresas, categorías y servicios. Selecciona un elemento para ver sus detalles.</p></div></div>
          <div className="flex items-center gap-2"><button type="button" onClick={printPlan} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><Download className="h-4 w-4" />PDF</button><Link to={`/e/${eventId}/agenda`} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><CalendarDays className="h-4 w-4" />Agenda</Link>{map && <div className="hidden rounded-xl border bg-white p-2 text-center sm:block"><QRCodeSVG value={`${window.location.origin}/expo/${eventId}/plano`} size={62} /><p className="text-[10px] text-slate-500">Compartir</p></div>}</div>
        </header>
        {message && !map ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">{message}</div> : <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_340px]">
          <section className="min-w-0 rounded-2xl border bg-white p-3 sm:p-5">
            <div className="mb-3 flex flex-wrap gap-2 print:hidden"><label className="relative min-w-[210px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={(event) => { setQuery(event.target.value); if (event.target.value.trim()) void track('search') }} placeholder="Buscar empresa, stand o categoría" className="w-full rounded-lg border px-9 py-2 text-sm" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Filtrar por categoría" className="rounded-lg border bg-white px-3 py-2 text-sm"><option value="">Todas las categorías</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select><button type="button" onClick={() => setFavoritesOnly(!favoritesOnly)} className={`inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold ${favoritesOnly ? 'border-amber-300 bg-amber-50 text-amber-800' : ''}`}><Star className="h-4 w-4" fill={favoritesOnly ? 'currentColor' : 'none'} />Mis favoritos</button><span className="rounded-lg bg-slate-100 px-3 py-2 text-sm text-slate-600">{filtered.length} elementos</span></div>
            <div className="overflow-auto rounded-xl border-2 border-slate-300 bg-slate-100 p-2"><PublicExhibitionCanvas columns={columns} rows={rows} elements={filtered} assignments={assignments} selectedId={selected?.id ?? null} onSelect={choose} /></div>
            <div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500 print:hidden"><span><i className="mr-1 inline-block h-3 w-3 rounded bg-emerald-100" />Stand disponible</span><span><i className="mr-1 inline-block h-3 w-3 rounded bg-sky-100" />Stand con empresa</span><span><i className="mr-1 inline-block h-3 w-3 rounded bg-slate-300" />Circulación / servicio</span></div>
            {routes.length > 0 && <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-3 print:hidden"><p className="flex items-center gap-2 text-sm font-semibold text-blue-900"><Navigation className="h-4 w-4" />Rutas accesibles disponibles</p><div className="mt-2 flex flex-wrap gap-2">{routes.map((route) => <button type="button" key={route.id} onClick={() => { setMessage(`Ruta “${route.name}” seleccionada. Sigue la señalización del recinto.`); void track('route') }} className="rounded-lg border border-blue-200 bg-white px-3 py-1.5 text-xs font-semibold text-blue-800">{route.name}{route.kind === 'accessible' ? ' · accesible' : ''}</button>)}</div></div>}
          </section>
          <aside className="flex flex-col gap-4 lg:sticky lg:top-4 lg:self-start print:hidden">
            {selected && <div className="order-first rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-wide" style={{ color: accent }}>{selected.element_type === 'stand' ? 'Stand seleccionado' : 'Punto de interés'}</p><h2 className="mt-1 text-lg font-bold">{selectedCompany || selected.label}</h2><p className="text-sm text-emerald-900">{selected.label} · {labelForType(selected.element_type ?? '')}</p></div><button type="button" onClick={() => choose(null)} aria-label="Cerrar detalle" className="rounded-lg p-1 text-emerald-800 hover:bg-emerald-100"><X className="h-4 w-4" /></button></div>{metadataText(selected, 'description') && <p className="mt-3 text-sm text-emerald-950">{metadataText(selected, 'description')}</p>}{selected.tags?.length ? <div className="mt-3 flex flex-wrap gap-1">{selected.tags.map((tag) => <span key={tag} className="rounded-full bg-white/70 px-2 py-1 text-xs text-emerald-900">{tag}</span>)}</div> : null}{sessions.filter((session) => session.venue_element_id === selected.id).length > 0 && <div className="mt-4 border-t border-emerald-200 pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-800">Sesiones en esta ubicación</p>{sessions.filter((session) => session.venue_element_id === selected.id).map((session) => <Link key={session.session_id} to={`/e/${eventId}/agenda?session=${session.session_id}`} className="mt-2 block rounded-lg bg-white/80 p-2 text-xs hover:bg-white"><b>{session.session_name}</b><span className="block text-emerald-800">{session.starts_at ? new Date(session.starts_at).toLocaleString('es-VE', { weekday: 'short', hour: '2-digit', minute: '2-digit' }) : 'Horario por confirmar'}{session.stage_name ? ` · ${session.stage_name}` : ''}</span></Link>)}</div>}<div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => toggleFavorite(selected)} className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 bg-white px-3 py-2 text-xs font-semibold"><Heart className="h-4 w-4" fill={favorites.includes(selected.id) ? 'currentColor' : 'none'} />{favorites.includes(selected.id) ? 'Guardado' : 'Guardar'}</button><button type="button" onClick={() => void shareSelected()} className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 bg-white px-3 py-2 text-xs font-semibold"><Share2 className="h-4 w-4" />Compartir</button></div></div>}
            <div className="order-last rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-2"><h2 className="font-semibold">Directorio de empresas</h2><span className="text-xs text-slate-500">{stands.length}</span></div><div className="mt-3 max-h-[52vh] space-y-2 overflow-auto">{stands.map((item) => <button type="button" key={item.id} onClick={() => choose(item)} className="flex w-full items-center justify-between rounded-lg border p-3 text-left text-sm hover:border-emerald-500"><span><b>{metadataText(item, 'company_name') || item.label}</b><span className="block text-xs text-slate-500">{item.label}{item.booth_type ? ` · ${item.booth_type}` : ''}</span></span><Star className={`h-4 w-4 ${favorites.includes(item.id) ? 'fill-amber-400 text-amber-400' : 'text-slate-300'}`} /></button>)}{!stands.length && <p className="text-sm text-slate-500">No hay coincidencias.</p>}</div><div className="mt-4 flex flex-wrap gap-2 border-t pt-3"><button type="button" onClick={() => setShowEmbed(!showEmbed)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold"><Code2 className="h-3.5 w-3.5" />Insertar plano</button><Link to={`/e/${eventId}/agenda`} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold"><CalendarDays className="h-3.5 w-3.5" />Ver agenda</Link></div>{showEmbed && <div className="mt-3 rounded-lg bg-slate-50 p-3"><p className="text-xs font-semibold">Código para tu sitio web</p><textarea readOnly value={embedCode} rows={4} className="mt-2 w-full rounded border bg-white p-2 text-[11px]" onFocus={(event) => event.currentTarget.select()} /><button type="button" onClick={() => { void navigator.clipboard?.writeText(embedCode); setMessage('Código copiado.') }} className="mt-2 rounded-lg bg-emerald-700 px-3 py-1.5 text-xs font-semibold text-white">Copiar código</button></div>}</div>
          </aside>
        </div>}
        <div className="fixed inset-x-3 bottom-3 z-20 flex items-center justify-between gap-2 rounded-2xl border bg-white/95 p-2 shadow-lg backdrop-blur lg:hidden print:hidden"><button type="button" onClick={() => setFavoritesOnly(!favoritesOnly)} className={`flex flex-1 items-center justify-center gap-1 rounded-xl px-3 py-2 text-xs font-semibold ${favoritesOnly ? 'bg-amber-100 text-amber-800' : ''}`}><Star className="h-4 w-4" fill={favoritesOnly ? 'currentColor' : 'none'} />Favoritos</button><button type="button" onClick={printPlan} className="flex flex-1 items-center justify-center gap-1 rounded-xl px-3 py-2 text-xs font-semibold"><Download className="h-4 w-4" />PDF</button><Link to={`/e/${eventId}/agenda`} className="flex flex-1 items-center justify-center gap-1 rounded-xl px-3 py-2 text-xs font-semibold"><CalendarDays className="h-4 w-4" />Agenda</Link></div>
      </div>
    </main>
  )
}
