import { useCallback, useEffect, useState } from 'react'
import { CheckCircle2, Send } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'

type Field = { key: string; label: string; type: 'text' | 'email' | 'tel' | 'textarea'; required?: boolean }
type Form = { id: string; title: string; description: string | null; fields: Field[]; consent_label: string }
function attribution() { const p = new URLSearchParams(window.location.search); let referrerHost: string | undefined; try { referrerHost = document.referrer ? new URL(document.referrer).hostname : undefined } catch { referrerHost = undefined }; return { campaign: p.get('utm_campaign') ?? undefined, source: p.get('utm_source') ?? undefined, medium: p.get('utm_medium') ?? undefined, referrerHost } }

export default function PublicLeadForm() {
  const { eventId, slug } = useParams(); const [form, setForm] = useState<Form | null>(null); const [answers, setAnswers] = useState<Record<string, string>>({}); const [consented, setConsented] = useState(false); const [error, setError] = useState<string | null>(null); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { if (!eventId || !slug) return; const { data, error: loadError } = await supabase.rpc('get_public_event_lead_form', { p_event_id: eventId, p_slug: slug }); if (loadError) setError(loadError.message); else setForm(((data ?? [])[0] ?? null) as Form | null); setLoading(false) }, [eventId, slug])
  useEffect(() => { void load() }, [load])
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!eventId || !slug) return; setError(null); const a = attribution(); const { error: submitError } = await supabase.rpc('submit_public_event_lead', { p_event_id: eventId, p_slug: slug, p_answers: answers, p_consented: consented, p_campaign: a.campaign, p_source: a.source, p_medium: a.medium, p_referrer_host: a.referrerHost }); if (submitError) setError(submitError.message); else setSent(true) }
  return <main className="grid min-h-[100dvh] place-items-center bg-zinc-50 px-4 py-8"><section className="w-full max-w-xl rounded-2xl border bg-white p-6 shadow-sm sm:p-8">{loading ? <p className="text-sm text-zinc-500">Cargando formulario…</p> : !form ? <><h1 className="text-xl font-bold">Formulario no disponible</h1><p className="mt-2 text-sm text-zinc-600">Este enlace puede haber vencido o no está publicado.</p></> : sent ? <div className="text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><h1 className="mt-4 text-2xl font-bold">¡Gracias!</h1><p className="mt-2 text-sm text-zinc-600">Recibimos tu solicitud. El organizador se pondrá en contacto contigo.</p></div> : <><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Información del evento</p><h1 className="mt-2 text-2xl font-bold">{form.title}</h1>{form.description && <p className="mt-2 text-sm text-zinc-600">{form.description}</p>}<form onSubmit={submit} className="mt-6 space-y-4">{form.fields.map((field) => <label key={field.key} className="block text-sm font-semibold">{field.label}{field.required && ' *'}{field.type === 'textarea' ? <textarea required={field.required} value={answers[field.key] ?? ''} onChange={(e) => setAnswers({ ...answers, [field.key]: e.target.value })} className="mt-1 min-h-28 w-full rounded-lg border border-zinc-300 px-3 py-2 font-normal" /> : <input required={field.required} type={field.type} value={answers[field.key] ?? ''} onChange={(e) => setAnswers({ ...answers, [field.key]: e.target.value })} className="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2 font-normal" />}</label>)}<label className="flex gap-3 rounded-xl bg-zinc-50 p-3 text-xs leading-5 text-zinc-700"><input required checked={consented} onChange={(e) => setConsented(e.target.checked)} type="checkbox" className="mt-1 h-4 w-4"/><span>{form.consent_label}</span></label>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-700 px-4 py-3 text-sm font-bold text-white"><Send className="h-4 w-4" />Enviar solicitud</button></form></>}</section></main>
}
