import { useEffect, useRef, useState } from 'react'
import { FloorplanEditor } from './FloorplanEditor'
import { fromVenueElement } from './adapter'
import type { FloorplanElement } from './model'
import { supabase } from '../../../lib/supabase'
import { useAutosave } from './useAutosave'
import { Link } from 'react-router-dom'

export function ConnectedFloorplanEditor({ mapId, eventId }: { mapId: string; eventId: string }) {
  const [mode, setMode] = useState<'design' | 'assign'>('design')
  const [elements, setElements] = useState<FloorplanElement[] | null>(null)
  const [draft, setDraft] = useState<FloorplanElement[] | null>(null)
  const [grid, setGrid] = useState({ columns: 18, rows: 12 })
  const [mapMetadata, setMapMetadata] = useState<Record<string, unknown>>({})
  const [error, setError] = useState<string | null>(null)
  const reconcileRef = useRef<(ids: Record<string, string>) => void>(() => undefined)
  const persistedIds = useRef(new Set<string>())
  useEffect(() => { void Promise.all([supabase.from('venue_map_elements').select('id,label,element_type,status,x,y,width,height,metadata').eq('map_id', mapId), supabase.from('venue_maps').select('metadata').eq('id', mapId).single()]).then(([{ data, error: loadError }, { data: map }]) => { if (loadError) setError(loadError.message); else { const loaded = (data ?? []).map(fromVenueElement); const metadata = (map?.metadata ?? {}) as Record<string, unknown> & { grid_columns?: number; grid_rows?: number }; persistedIds.current = new Set(loaded.map((item) => item.id)); setMapMetadata(metadata); setGrid({ columns: metadata.grid_columns ?? 18, rows: metadata.grid_rows ?? 12 }); setElements(loaded); setDraft(loaded) } }) }, [mapId])
  const autosave = useAutosave(draft, async (next) => { if (!next) return; const nextIds = new Set(next.map((item) => item.id)); const removed = [...persistedIds.current].filter((id) => !nextIds.has(id)); if (removed.length) { const { error: deleteError } = await supabase.from('venue_map_elements').delete().in('id', removed); if (deleteError) throw deleteError; removed.forEach((id) => persistedIds.current.delete(id)) }; const ids: Record<string, string> = {}; const created = next.filter((item) => !persistedIds.current.has(item.id)); for (const item of created) { const { data, error: insertError } = await supabase.from('venue_map_elements').insert({ map_id: mapId, element_type: item.kind === 'stand' ? 'stand' : item.kind === 'aisle' ? 'aisle' : item.objectType === 'access' || item.objectType === 'door' || item.objectType === 'security' ? 'access_point' : 'zone', label: item.label, x: item.x, y: item.y, width: item.width, height: item.height, status: item.kind === 'stand' ? 'available' : 'blocked', metadata: { floorplan_kind: item.kind === 'zone' && item.objectType === 'blank' ? 'blank' : item.kind === 'zone' && item.objectType === 'special' ? 'special' : item.objectType ? 'object' : item.kind, object_type: item.objectType, purpose: item.purpose } }).select('id').single(); if (insertError) throw insertError; ids[item.id] = data.id; persistedIds.current.add(data.id) }; if (Object.keys(ids).length) reconcileRef.current(ids); const updates = next.filter((item) => persistedIds.current.has(item.id)).map((item) => supabase.from('venue_map_elements').update({ label: item.label, x: item.x, y: item.y, width: item.width, height: item.height, metadata: { floorplan_kind: item.kind === 'zone' && item.objectType === 'blank' ? 'blank' : item.kind === 'zone' && item.objectType === 'special' ? 'special' : item.objectType ? 'object' : item.kind, object_type: item.objectType, purpose: item.purpose } }).eq('id', item.id)); const results = await Promise.all(updates); const failed = results.find((result) => result.error)?.error; if (failed) throw failed })
  if (!elements) return <p className="rounded-xl border bg-white p-4 text-sm text-zinc-600">Cargando plano…</p>
  async function changeGrid(columns: number, rows: number) { if (!Number.isInteger(columns) || !Number.isInteger(rows) || columns < 1 || rows < 1 || elements?.some((item) => item.x + item.width > columns || item.y + item.height > rows)) { setError('No puedes reducir la cuadrícula sobre elementos existentes.'); return }; setGrid({ columns, rows }); const metadata = { ...mapMetadata, grid_columns: columns, grid_rows: rows }; const { error: gridError } = await supabase.from('venue_maps').update({ metadata }).eq('id', mapId); if (gridError) setError(gridError.message); else { setMapMetadata(metadata); setError(null) } }
  return <section>{error && <p className="mb-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mb-4 flex items-center gap-2 rounded-xl border bg-white p-2"><button type="button" onClick={() => setMode('design')} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode === 'design' ? 'bg-emerald-700 text-white' : ''}`}>Diseñar plano</button><button type="button" onClick={() => setMode('assign')} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode === 'assign' ? 'bg-emerald-700 text-white' : ''}`}>Asignar empresas</button><span className="ml-auto text-xs text-zinc-500">{autosave === 'saving' ? 'Guardando…' : autosave === 'saved' ? 'Guardado' : autosave === 'error' ? 'Error al guardar' : ''}</span></div>{mode === 'design' ? <FloorplanEditor initial={elements} columns={grid.columns} rows={grid.rows} onGridChange={(columns, rows) => void changeGrid(columns, rows)} onChange={(next, reconcile) => { reconcileRef.current = reconcile; setDraft(next) }} /> : <div className="rounded-xl border bg-white p-4 text-sm text-zinc-600"><p>Gestiona empresas, crea expositores nuevos y asigna cada stand desde el módulo comercial.</p><Link to={`/admin/expositores/${eventId}`} className="mt-3 inline-flex rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Abrir expositores y asignaciones</Link></div>}</section>
}
