import { useEffect, useState } from 'react'
import { FloorplanCanvas } from './FloorplanCanvas'
import { FloorplanPalette } from './FloorplanPalette'
import { intersects, palette } from './model'
import type { FloorplanElement } from './model'
import { useFloorplanHistory } from './useFloorplanHistory'

type Tool = typeof palette[number]['objectType']

export function FloorplanEditor({ initial, columns, rows, onGridChange, onChange }: { initial: FloorplanElement[]; columns: number; rows: number; onGridChange: (columns: number, rows: number) => void; onChange?: (elements: FloorplanElement[], reconcile: (ids: Record<string, string>) => void) => void }) {
  const [tool, setTool] = useState<Tool | null>(null); const [aisleAxis, setAisleAxis] = useState<'vertical' | 'horizontal'>('vertical'); const [selectedId, setSelectedId] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const { current, commit, reconcileIds, undo, redo, canUndo, canRedo } = useFloorplanHistory(initial)
  useEffect(() => { onChange?.(current, reconcileIds) }, [current, onChange, reconcileIds])
  function place(nextTool: Tool, x: number, y: number) { const preset = palette.find((item) => item.objectType === nextTool); if (!preset) return; const count = current.filter((item) => item.label === preset.label || item.label.startsWith(`${preset.label} `)).length + 1; if (nextTool === 'aisle') { const vertical = aisleAxis === 'vertical'; const shifted = current.map((item) => vertical ? (item.x >= x ? { ...item, x: item.x + 1 } : item) : (item.y >= y ? { ...item, y: item.y + 1 } : item)); commit([...shifted, { id: `local-${crypto.randomUUID()}`, label: `${preset.label} ${count}`, kind: 'aisle', x: vertical ? x : 0, y: vertical ? 0 : y, width: vertical ? 1 : columns, height: vertical ? rows : 1 }]); onGridChange(vertical ? columns + 1 : columns, vertical ? rows : rows + 1); setNotice(`Pasillo ${vertical ? 'vertical' : 'horizontal'} creado; los elementos posteriores fueron desplazados.`); setTool(null); return }; const kind = nextTool === 'stand' ? 'stand' : nextTool === 'blank' || nextTool === 'special' ? 'zone' : 'object'; commit([...current, { id: `local-${crypto.randomUUID()}`, label: `${preset.label} ${count}`, kind, objectType: nextTool === 'stand' ? undefined : nextTool, x, y, width: preset.width, height: preset.height }]); setTool(null) }
  function resize(axis: 'x' | 'y', delta: number) { const item = current.find((entry) => entry.id === selectedId); if (!item) return; const next = { ...item, [axis === 'x' ? 'width' : 'height']: (axis === 'x' ? item.width : item.height) + delta }; if (next.width < 1 || next.height < 1 || next.x + next.width > columns || next.y + next.height > rows || current.some((entry) => entry.id !== item.id && intersects(next, entry))) { setNotice('No hay espacio para cambiar ese tamaño.'); return }; setNotice(null); commit(current.map((entry) => entry.id === item.id ? next : entry)) }
  function move(id: string, x: number, y: number) { const item = current.find((entry) => entry.id === id); if (!item) return; const next = { ...item, x, y }; if (x + item.width > columns || y + item.height > rows || current.some((entry) => entry.id !== id && intersects(next, entry))) { setNotice('No se puede mover: la posición está ocupada o fuera del plano.'); return }; setNotice(null); commit(current.map((entry) => entry.id === id ? next : entry)) }
  function remove() { if (!selectedId) return; commit(current.filter((item) => item.id !== selectedId)); setSelectedId(null) }
  function updateSelected(change: Partial<FloorplanElement>) { if (!selectedId) return; commit(current.map((item) => item.id === selectedId ? { ...item, ...change } : item)) }
  const hasOverflow = current.some((item) => item.x + item.width > columns || item.y + item.height > rows)
  const selected = current.find((item) => item.id === selectedId)
  return <div className="grid gap-4 lg:grid-cols-[180px_1fr]"><FloorplanPalette active={tool} onChoose={setTool} /><section><div className="mb-2 flex flex-wrap items-center gap-2"><button type="button" disabled={!canUndo} onClick={undo} className="rounded border px-2 py-1 text-xs disabled:opacity-40">Deshacer</button><button type="button" disabled={!canRedo} onClick={redo} className="rounded border px-2 py-1 text-xs disabled:opacity-40">Rehacer</button><label className="ml-auto text-xs">Columnas <input type="number" min="1" value={columns} onChange={(event) => onGridChange(Number(event.target.value), rows)} className="ml-1 w-14 rounded border p-1" /></label><label className="text-xs">Filas <input type="number" min="1" value={rows} onChange={(event) => onGridChange(columns, Number(event.target.value))} className="ml-1 w-14 rounded border p-1" /></label></div>{selected && <div className="mb-2 grid gap-2 rounded border bg-white p-3 text-xs sm:grid-cols-2"><label>Nombre<input value={selected.label} onChange={(event) => updateSelected({ label: event.target.value })} className="mt-1 w-full rounded border p-2 text-sm" /></label><label>Objetivo / uso<input value={selected.purpose ?? ''} onChange={(event) => updateSelected({ purpose: event.target.value })} placeholder="Ej. salida de emergencia" className="mt-1 w-full rounded border p-2 text-sm" /></label></div>}{tool === 'aisle' && <div className="mb-2 flex items-center gap-2 rounded bg-sky-50 p-2 text-xs text-sky-950"><span>Inserta una franja y desplaza el contenido:</span><button type="button" onClick={() => setAisleAxis('vertical')} className={`rounded px-2 py-1 ${aisleAxis === 'vertical' ? 'bg-sky-700 text-white' : 'border'}`}>Vertical</button><button type="button" onClick={() => setAisleAxis('horizontal')} className={`rounded px-2 py-1 ${aisleAxis === 'horizontal' ? 'bg-sky-700 text-white' : 'border'}`}>Horizontal</button></div>}{notice && <p className="mb-2 rounded bg-amber-50 p-2 text-xs text-amber-900">{notice}</p>}{hasOverflow && <p className="mb-2 rounded bg-amber-50 p-2 text-xs text-amber-900">Amplía la cuadrícula: contiene elementos fuera de estos límites.</p>}<FloorplanCanvas elements={current} columns={columns} rows={rows} activeTool={tool} selectedId={selectedId} onSelect={setSelectedId} onResize={resize} onPlace={place} onMove={move} onDelete={remove} /></section></div>
}
