import { useMemo, useState } from 'react'
import { DragDropProvider, useDraggable, useDroppable } from '@dnd-kit/react'
import { intersects, palette } from './model'
import type { FloorplanElement } from './model'

type Tool = typeof palette[number]['objectType']
const cellId = (x: number, y: number) => `cell:${x}:${y}`
const overlayTypes = new Set(['plant', 'table', 'sofa', 'door', 'access', 'security', 'flow_arrow'])
const isOverlay = (item: FloorplanElement) => !!item.objectType && overlayTypes.has(item.objectType)

function Cell({ x, y, onHover, onLeave, onPlace }: { x: number; y: number; onHover: () => void; onLeave: () => void; onPlace: () => void }) {
  const { ref, isDropTarget } = useDroppable({ id: cellId(x, y) })
  return <button ref={ref} type="button" onMouseEnter={onHover} onMouseLeave={onLeave} onClick={onPlace} className={`border border-zinc-100 ${isDropTarget ? 'bg-emerald-100' : ''}`} style={{ gridColumnStart: x + 1, gridRowStart: y + 1 }} aria-label={`Columna ${x + 1}, fila ${y + 1}`} />
}

function ElementVisual({ item }: { item: FloorplanElement }) {
  switch (item.objectType) {
    case 'door': return <span className="relative h-full w-full overflow-hidden rounded-sm border-b-4 border-zinc-700 bg-white"><span className="absolute bottom-0 left-0 h-[170%] w-[170%] origin-bottom-left rounded-full border border-dashed border-zinc-400" /><span className="absolute bottom-0 left-0 h-[3px] w-[72%] origin-bottom-left -rotate-45 bg-zinc-700" /><span className="absolute right-1 top-1 text-[9px] font-bold text-zinc-600">ENTRADA</span></span>
    case 'access': return <span className="flex h-full w-full items-center justify-center rounded-md border-2 border-sky-700 bg-sky-50 text-center text-[9px] font-bold text-sky-900"><span className="border-x-2 border-sky-700 px-1">↔<br />ACCESO</span></span>
    case 'security': return <span className="flex h-full w-full items-center justify-center rounded-full border-2 border-indigo-700 bg-indigo-100 text-center text-[9px] font-bold text-indigo-900">✓<br />CTRL</span>
    case 'plant': return <span className="flex h-full w-full items-center justify-center rounded-full border-2 border-emerald-700 bg-emerald-100 text-xl leading-none">✳</span>
    case 'table': return <span className="flex h-full w-full items-center justify-center rounded-full border-4 border-amber-800 bg-amber-100 text-[10px] font-bold text-amber-950">MESA</span>
    case 'sofa': return <span className="relative flex h-full w-full items-center justify-center rounded-lg border-4 border-amber-900 bg-amber-200 text-[10px] font-bold text-amber-950 before:absolute before:inset-x-2 before:top-1 before:h-2 before:rounded bg-amber-700">SOFÁ</span>
    case 'flow_arrow': return <span className="flex h-full w-full items-center justify-center rounded-full border-2 border-fuchsia-700 bg-fuchsia-100 text-xl font-black text-fuchsia-800"><span style={{ transform: `rotate(${item.rotation ?? 0}deg)` }}>→</span></span>
    case 'column': return <span className="flex h-full w-full items-center justify-center rounded-full border-4 border-zinc-700 bg-zinc-300 text-[9px] font-bold">COL</span>
    default: return <span className="flex h-full w-full items-center justify-center px-1 text-center">{item.label}</span>
  }
}

function DraggableElement({ item, selected, activeTool, onSelect, onResize, onPlace, onHover, onLeave }: { item: FloorplanElement; selected: boolean; activeTool: Tool | null; onSelect: () => void; onResize: (axis: 'x' | 'y', delta: number) => void; onPlace: (tool: Tool, x: number, y: number) => void; onHover: () => void; onLeave: () => void }) {
  const { ref, isDragging } = useDraggable({ id: item.id })
  return <div className={`relative ${isOverlay(item) ? 'z-20' : 'z-10'}`} style={{ gridColumn: `${item.x + 1} / span ${item.width}`, gridRow: `${item.y + 1} / span ${item.height}`, opacity: isDragging ? 0.45 : 1 }}><button ref={ref} type="button" onMouseEnter={onHover} onMouseLeave={onLeave} onClick={() => activeTool ? onPlace(activeTool, item.x, item.y) : onSelect()} className={`flex h-full w-full items-center justify-center rounded-lg border p-1 text-xs font-semibold ${item.kind === 'stand' ? 'border-emerald-300 bg-emerald-50' : item.kind === 'aisle' ? 'border-slate-300 bg-slate-100/70' : 'border-zinc-400 bg-zinc-100/80'} ${selected ? 'ring-2 ring-emerald-700 ring-offset-2' : ''}`} aria-label={item.label}><ElementVisual item={item} /></button>{selected && <><button type="button" onClick={() => onResize('x', 1)} className="absolute -right-2 top-1/2 h-4 w-4 -translate-y-1/2 rounded-full bg-emerald-700 text-[10px] text-white shadow" aria-label="Ampliar hacia la derecha">+</button><button type="button" onClick={() => onResize('y', 1)} className="absolute bottom-[-8px] left-1/2 h-4 w-4 -translate-x-1/2 rounded-full bg-emerald-700 text-[10px] text-white shadow" aria-label="Ampliar hacia abajo">+</button><button type="button" onClick={() => onResize('x', -1)} className="absolute -left-2 top-1/2 h-4 w-4 -translate-y-1/2 rounded-full bg-white text-[10px] shadow" aria-label="Reducir ancho">−</button><button type="button" onClick={() => onResize('y', -1)} className="absolute left-1/2 top-[-8px] h-4 w-4 -translate-x-1/2 rounded-full bg-white text-[10px] shadow" aria-label="Reducir alto">−</button></>}</div>
}

export function FloorplanCanvas({ elements, columns = 18, rows = 12, activeTool, aisleAxis, selectedId, onSelect, onResize, onPlace, onMove, onDelete }: { elements: FloorplanElement[]; columns?: number; rows?: number; activeTool: Tool | null; aisleAxis: 'vertical' | 'horizontal'; selectedId: string | null; onSelect: (id: string) => void; onResize: (axis: 'x' | 'y', delta: number) => void; onPlace: (tool: Tool, x: number, y: number) => void; onMove: (id: string, x: number, y: number) => void; onDelete: () => void }) {
  const [hover, setHover] = useState<{ x: number; y: number } | null>(null)
  const preview = useMemo(() => { const item = palette.find((entry) => entry.objectType === activeTool); return item && hover ? { ...item, ...hover, width: activeTool === 'aisle' ? aisleAxis === 'vertical' ? 1 : 3 : item.width, height: activeTool === 'aisle' ? aisleAxis === 'vertical' ? 3 : 1 : item.height } : null }, [activeTool, aisleAxis, hover])
  const outside = !!preview && (preview.x + preview.width > columns || preview.y + preview.height > rows)
  const blocked = !!preview && (outside || (activeTool !== 'aisle' && elements.some((item) => intersects(item, preview))))
  return <DragDropProvider onDragEnd={(event) => { if (event.canceled) return; const id = String(event.operation.source?.id ?? ''); const match = /^cell:(\d+):(\d+)$/.exec(String(event.operation.target?.id ?? '')); if (match) onMove(id, Number(match[1]), Number(match[2])) }}><div className="overflow-auto rounded-xl border bg-white p-2">{selectedId && <div className="mb-2 flex items-center justify-between rounded-lg bg-zinc-50 px-3 py-2 text-xs"><span>Elemento seleccionado: arrástralo o usa los tiradores.</span><button type="button" onClick={onDelete} className="rounded border border-red-200 px-2 py-1 font-semibold text-red-700">Eliminar</button></div>}<div className="grid min-w-[864px] gap-px rounded-lg bg-zinc-300 p-px" style={{ gridTemplateColumns: `repeat(${columns}, minmax(48px, 1fr))`, gridTemplateRows: `repeat(${rows}, minmax(48px, 1fr))` }}>{Array.from({ length: columns * rows }, (_, index) => { const x = index % columns; const y = Math.floor(index / columns); return <Cell key={index} x={x} y={y} onHover={() => setHover({ x, y })} onLeave={() => setHover(null)} onPlace={() => { if (activeTool && !blocked) onPlace(activeTool, x, y) }} /> })}{elements.map((item) => <DraggableElement key={item.id} item={item} selected={selectedId === item.id} activeTool={activeTool} onSelect={() => onSelect(item.id)} onResize={onResize} onPlace={onPlace} onHover={() => setHover({ x: item.x, y: item.y })} onLeave={() => setHover(null)} />)}{preview && <div className={`pointer-events-none z-30 rounded-lg border-2 border-dashed p-2 text-xs ${blocked ? 'border-red-500 bg-red-100/80' : 'border-emerald-600 bg-emerald-100/80'}`} style={{ gridColumn: `${preview.x + 1} / span ${preview.width}`, gridRow: `${preview.y + 1} / span ${preview.height}` }}>{blocked ? outside ? 'Fuera del plano' : 'Espacio ocupado' : `Insertar ${preview.label}`}</div>}</div></div></DragDropProvider>
}
