import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, ArrowRight, BarChart3, CheckCircle2, ClipboardList, CreditCard, Users } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

type Metrics = { total_registrations: number; pending_payments: number; confirmed_registrations: number; attended_registrations: number; landing_views: number; registration_starts: number; registration_completions: number; exhibitor_profiles_pending: number; stands_unassigned: number }
const empty: Metrics = { total_registrations: 0, pending_payments: 0, confirmed_registrations: 0, attended_registrations: 0, landing_views: 0, registration_starts: 0, registration_completions: 0, exhibitor_profiles_pending: 0, stands_unassigned: 0 }

export default function EventOverview() {
  const { eventId } = useParams(); const [metrics, setMetrics] = useState<Metrics>(empty); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { if (!eventId) return; const { data, error: rpcError } = await supabase.rpc('get_event_growth_metrics', { p_event_id: eventId }); if (rpcError) { setError(rpcError.message); return }; setMetrics((Array.isArray(data) ? data[0] : data) as Metrics ?? empty) }, [eventId])
  useEffect(() => { void load() }, [load])
  const conversion = metrics.landing_views ? Math.round((metrics.registration_completions / metrics.landing_views) * 100) : 0
  const alerts = [
    ...(metrics.pending_payments ? [{ label: `${metrics.pending_payments} pagos por revisar`, to: `/admin/eventos/${eventId}/registros` }] : []),
    ...(metrics.exhibitor_profiles_pending ? [{ label: `${metrics.exhibitor_profiles_pending} perfiles de expositores pendientes`, to: `/admin/expositores/${eventId}` }] : []),
    ...(metrics.stands_unassigned ? [{ label: `${metrics.stands_unassigned} stands sin asignar`, to: `/admin/stands/${eventId}` }] : []),
  ]
  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Centro de control</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Resumen del evento</h1><p className="mt-1 text-sm text-zinc-600">Estado operativo, ventas y conversión en un solo lugar.</p></div><Link to={`/admin/eventos/${eventId}/conversiones`} className="inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white"><BarChart3 className="h-4 w-4" />Ver embudo</Link></div>
    {error && <p role="alert" className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Las métricas estarán disponibles al aplicar la migración de conversión: {error}</p>}
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{label:'Registros',value:metrics.total_registrations,icon:ClipboardList},{label:'Pagos pendientes',value:metrics.pending_payments,icon:CreditCard},{label:'Confirmados',value:metrics.confirmed_registrations,icon:CheckCircle2},{label:'Asistentes',value:metrics.attended_registrations,icon:Users}].map(({label,value,icon:Icon})=><article key={label} className="rounded-xl border bg-white p-4"><Icon className="h-5 w-5 text-emerald-700"/><p className="mt-3 text-sm text-zinc-500">{label}</p><p className="text-3xl font-bold">{value}</p></article>)}</section>
    <section className="mt-7 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-zinc-500">Promoción y conversiones</p><h2 className="mt-1 text-lg font-bold">Embudo de registro</h2></div><b className="text-2xl text-emerald-700">{conversion}%</b></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[{label:'Visitas',value:metrics.landing_views},{label:'Inicios',value:metrics.registration_starts},{label:'Completados',value:metrics.registration_completions}].map(item=><div key={item.label} className="rounded-xl bg-zinc-50 p-4"><p className="text-sm text-zinc-500">{item.label}</p><p className="mt-1 text-2xl font-bold">{item.value}</p></div>)}</div><Link to={`/admin/eventos/${eventId}/conversiones`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Analizar campañas <ArrowRight className="h-4 w-4" /></Link></article>
      <article className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase tracking-wide text-zinc-500">Siguientes acciones</p><h2 className="mt-1 text-lg font-bold">Pendientes del evento</h2>{alerts.length ? <ul className="mt-4 space-y-2">{alerts.map(alert=><li key={alert.label}><Link to={alert.to} className="flex items-center justify-between gap-2 rounded-lg bg-amber-50 px-3 py-3 text-sm font-semibold text-amber-950"><span>{alert.label}</span><ArrowRight className="h-4 w-4" /></Link></li>)}</ul> : <div className="mt-5 text-center text-sm text-zinc-600"><CheckCircle2 className="mx-auto h-7 w-7 text-emerald-600"/><p className="mt-2">No hay pendientes críticos detectados.</p></div>}<p className="mt-4 flex gap-2 text-xs leading-5 text-zinc-500"><AlertTriangle className="h-4 w-4 shrink-0"/>Las alertas se actualizan con los datos operativos del evento.</p></article></section>
  </main>
}
