import { useCallback, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Circle, Rocket } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

type Event = { name: string; description: string | null; status: string; registration_deadline: string | null; config: Record<string, unknown> | null }
export default function EventLaunchChecklist() {
  const { eventId } = useParams(); const [event, setEvent] = useState<Event | null>(null); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { if (!eventId) return; const { data, error: loadError } = await supabase.from('events').select('name,description,status,registration_deadline,config').eq('id', eventId).maybeSingle(); if (loadError) setError(loadError.message); else setEvent(data as Event | null) }, [eventId])
  useEffect(() => { void load() }, [load])
  const tasks = useMemo(() => [{ label: 'Datos básicos del evento', detail: 'Nombre y descripción para presentar el evento.', done: Boolean(event?.name && event.description), to: `/admin/eventos/${eventId}/administrar` }, { label: 'Registro y pagos', detail: 'Configura la modalidad de registro antes de anunciarlo.', done: Boolean(event?.config?.registration_mode), to: `/admin/eventos/${eventId}/registros` }, { label: 'Promoción', detail: 'Crea un formulario o comparte el enlace de registro con UTM.', done: false, to: `/admin/eventos/${eventId}/formularios` }, { label: 'Programa o exposición', detail: 'Completa la agenda, el plano o los stands según el tipo de evento.', done: false, to: `/admin/eventos/${eventId}/resumen` }, { label: 'Operación presencial', detail: 'Prepara acreditación, personal y puntos de acceso.', done: false, to: `/admin/operacion-plano/${eventId}` }, { label: 'Publicación', detail: 'Publica cuando el recorrido público esté listo.', done: event?.status === 'published', to: `/admin/eventos/${eventId}/administrar` }], [event, eventId])
  const completed = tasks.filter((task) => task.done).length
  return <main className="mx-auto max-w-5xl px-4 py-6 sm:px-7"><header><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Lanzamiento</p><h1 className="mt-1 text-2xl font-bold">Checklist del evento</h1><p className="mt-1 text-sm text-zinc-600">Una revisión rápida antes de anunciar o abrir el evento al público.</p></header>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="mt-6 rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="font-bold">Preparación actual</h2><p className="text-sm text-zinc-600">{completed} de {tasks.length} verificaciones detectadas automáticamente.</p></div><Rocket className="h-7 w-7 text-emerald-700" /></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-zinc-100"><div className="h-full bg-emerald-600" style={{ width: `${Math.round((completed / tasks.length) * 100)}%` }} /></div><div className="mt-6 space-y-3">{tasks.map((task) => <Link key={task.label} to={task.to} className="flex items-start gap-3 rounded-xl border border-zinc-200 p-4 transition hover:border-emerald-300 hover:bg-emerald-50"><span className="mt-0.5 text-emerald-700">{task.done ? <CheckCircle2 className="h-5 w-5"/> : <Circle className="h-5 w-5"/>}</span><span><b className="block text-sm">{task.label}</b><span className="mt-1 block text-sm text-zinc-600">{task.detail}</span></span></Link>)}</div></section><p className="mt-4 text-xs leading-5 text-zinc-500">Las tareas que dependen de contenido operativo se confirman en sus módulos para evitar marcar trabajo como listo sin evidencia.</p></main>
}
