import { useCallback, useEffect, useMemo, useState } from 'react'
import { Copy, ExternalLink, FileText, Plus, Send, Trash2 } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

type Field = { key: string; label: string; type: 'text' | 'email' | 'tel' | 'textarea'; required?: boolean }
type Form = { id: string; slug: string; title: string; description: string | null; form_type: string; fields: Field[]; published: boolean }
type Submission = { id: string; form_id: string; form_title: string; answers: Record<string, string>; campaign: string | null; source: string | null; medium: string | null; created_at: string }
const defaults: Field[] = [{ key: 'nombre', label: 'Nombre completo', type: 'text', required: true }, { key: 'correo', label: 'Correo electrónico', type: 'email', required: true }, { key: 'empresa', label: 'Empresa', type: 'text' }, { key: 'mensaje', label: '¿Cómo podemos ayudarte?', type: 'textarea' }]

export default function EventLeadForms() {
  const { eventId } = useParams()
  const [forms, setForms] = useState<Form[]>([]); const [submissions, setSubmissions] = useState<Submission[]>([])
  const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  const [draft, setDraft] = useState({ title: 'Solicita información', slug: 'solicita-informacion', form_type: 'contact', description: 'Déjanos tus datos y te contactaremos.' })
  const load = useCallback(async () => {
    if (!eventId) return
    const [{ data: formsData, error: formsError }, { data: leadsData, error: leadsError }] = await Promise.all([
      supabase.from('event_lead_forms').select('id,slug,title,description,form_type,fields,published').eq('event_id', eventId).order('created_at', { ascending: false }),
      supabase.rpc('get_event_lead_submissions', { p_event_id: eventId }),
    ])
    if (formsError || leadsError) setError(formsError?.message ?? leadsError?.message ?? 'No se pudo cargar la captación.')
    else { setForms((formsData ?? []) as Form[]); setSubmissions((leadsData ?? []) as Submission[]) }
  }, [eventId])
  useEffect(() => { void load() }, [load])
  const total = useMemo(() => submissions.length, [submissions])
  async function createForm(event: React.FormEvent) {
    event.preventDefault(); if (!eventId) return; setSaving(true); setError(null)
    const slug = draft.slug.toLowerCase().trim().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '')
    const { error: saveError } = await supabase.from('event_lead_forms').insert({ event_id: eventId, organization_id: (await supabase.from('events').select('organization_id').eq('id', eventId).single()).data?.organization_id, slug, title: draft.title.trim(), description: draft.description.trim() || null, form_type: draft.form_type, fields: defaults })
    setSaving(false); if (saveError) setError(saveError.message); else { setDraft({ title: 'Solicita información', slug: 'solicita-informacion', form_type: 'contact', description: 'Déjanos tus datos y te contactaremos.' }); await load() }
  }
  async function publish(form: Form, published: boolean) { const { error: updateError } = await supabase.from('event_lead_forms').update({ published }).eq('id', form.id); if (updateError) setError(updateError.message); else await load() }
  async function remove(form: Form) { if (!window.confirm(`Eliminar “${form.title}” y sus respuestas?`)) return; const { error: deleteError } = await supabase.from('event_lead_forms').delete().eq('id', form.id); if (deleteError) setError(deleteError.message); else await load() }
  function publicUrl(form: Form) { return `${window.location.origin}/e/${eventId}/interes/${form.slug}` }
  async function copy(form: Form) { await navigator.clipboard.writeText(publicUrl(form)); window.alert('Enlace copiado.') }
  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Promoción y conversiones</p><h1 className="mt-1 text-2xl font-bold">Formularios de interés</h1><p className="mt-1 text-sm text-zinc-600">Publica un formulario para prospectos, expositores, patrocinantes o suscriptores.</p></div><Link to={`/admin/eventos/${eventId}/conversiones`} className="text-sm font-semibold text-emerald-700">Volver al embudo</Link></header>
    {error && <p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={createForm} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Crear formulario</h2><p className="mt-1 text-sm text-zinc-600">Incluye consentimiento y campos básicos; los leads no se exponen públicamente.</p><label className="mt-4 block text-sm font-semibold">Objetivo<select value={draft.form_type} onChange={(e) => setDraft({ ...draft, form_type: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"><option value="contact">Contacto</option><option value="pre_registration">Pre-registro</option><option value="exhibitor">Interés de expositor</option><option value="sponsorship">Interés de patrocinio</option><option value="newsletter">Newsletter</option></select></label><label className="mt-3 block text-sm font-semibold">Título<input required value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" /></label><label className="mt-3 block text-sm font-semibold">Enlace corto<input required value={draft.slug} onChange={(e) => setDraft({ ...draft, slug: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" /></label><label className="mt-3 block text-sm font-semibold">Descripción<textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border px-3 py-2 font-normal" /></label><button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Plus className="h-4 w-4" />{saving ? 'Creando…' : 'Crear borrador'}</button></form>
      <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Formularios publicados</h2><p className="text-sm text-zinc-600">{forms.length} creados · {total} respuestas recibidas</p></div><FileText className="h-5 w-5 text-emerald-700" /></div><div className="mt-4 space-y-3">{forms.length ? forms.map((form) => <article key={form.id} className="rounded-xl border border-zinc-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{form.title}</h3><p className="mt-1 text-xs text-zinc-500">/{form.slug} · {form.form_type} · {form.published ? 'Publicado' : 'Borrador'}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => void publish(form, !form.published)} className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold">{form.published ? 'Despublicar' : 'Publicar'}</button><button onClick={() => void copy(form)} className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold"><Copy className="inline h-3.5 w-3.5" /> Copiar</button>{form.published && <a href={publicUrl(form)} target="_blank" rel="noreferrer" className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold"><ExternalLink className="inline h-3.5 w-3.5" /> Ver</a>}<button onClick={() => void remove(form)} className="rounded-lg border border-red-200 px-2.5 py-1.5 text-xs font-semibold text-red-700"><Trash2 className="h-3.5 w-3.5" /></button></div></div></article>) : <p className="py-8 text-center text-sm text-zinc-500">Aún no hay formularios creados.</p>}</div></section></section>
    <section className="mt-5 rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Send className="h-5 w-5 text-emerald-700"/><div><h2 className="font-bold">Leads recibidos</h2><p className="text-sm text-zinc-600">Solo miembros de esta organización pueden ver estos datos.</p></div></div>{submissions.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase text-zinc-500"><tr><th className="p-2">Formulario</th><th className="p-2">Datos</th><th className="p-2">Origen</th><th className="p-2">Fecha</th></tr></thead><tbody>{submissions.map((lead) => <tr key={lead.id} className="border-b last:border-0"><td className="p-2 font-semibold">{lead.form_title}</td><td className="p-2">{Object.entries(lead.answers).filter(([, value]) => value).map(([key, value]) => <p key={key}>{key}: {value}</p>)}</td><td className="p-2">{[lead.source, lead.medium, lead.campaign].filter(Boolean).join(' / ') || 'Directo'}</td><td className="p-2 whitespace-nowrap">{new Date(lead.created_at).toLocaleString('es-VE')}</td></tr>)}</tbody></table></div> : <p className="mt-5 text-sm text-zinc-500">No hay leads todavía.</p>}</section>
  </main>
}
