import { useCallback, useEffect, useState } from 'react'
import { Copy, ExternalLink, Globe2, ImagePlus, Save, Trash2 } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import type { LandingConfig, LandingTemplate } from '../../components/EventPublicLanding'
import { supabase } from '../../lib/supabase'

const initial: LandingConfig = { template: 'summit', eyebrow: 'Próximamente', headline: '', subheadline: '', cta_label: 'Registrarme', hero_image_url: '', hero_images: [], gallery_images: [], logo_url: '', primary_color: '', location: '', intro_title: '', intro_body: '', brochure_label: 'Descargar información', brochure_url: '', show_agenda: true, show_exhibition: true, show_interest: true }
type Event = { id: string; name: string; organization_id: string; config: Record<string, unknown> | null }
type Domain = { slug: string; custom_hostname: string | null }
const input = 'mt-1 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 font-normal outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100'
const images = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []

export default function EventLandingAdmin() {
  const { eventId } = useParams(); const [event, setEvent] = useState<Event | null>(null); const [domain, setDomain] = useState<Domain | null>(null); const [draft, setDraft] = useState<LandingConfig>(initial); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false)
  const load = useCallback(async () => { if (!eventId) return; const { data, error } = await supabase.from('events').select('id,name,organization_id,config').eq('id', eventId).maybeSingle(); if (error || !data) { setMessage(error?.message ?? 'Evento no encontrado.'); return }; const loaded = data as Event; setEvent(loaded); setDraft({ ...initial, ...((loaded.config?.public_landing ?? {}) as LandingConfig) }); const { data: org } = await supabase.from('organizations').select('slug,custom_hostname').eq('id', loaded.organization_id).maybeSingle(); setDomain(org as Domain | null) }, [eventId]); useEffect(() => { void load() }, [load])
  function set<K extends keyof LandingConfig>(key: K, value: LandingConfig[K]) { setDraft((current) => ({ ...current, [key]: value })) }
  async function save(formEvent: React.FormEvent) { formEvent.preventDefault(); if (!event) return; setSaving(true); setMessage(null); const config = { ...(event.config ?? {}), public_landing: draft }; const { error } = await supabase.from('events').update({ config }).eq('id', event.id); setSaving(false); if (error) setMessage(error.message); else { setEvent({ ...event, config }); setMessage('Landing guardada. Publica el evento para mostrarla en la raíz de su dominio.') } }
  async function uploadImage(file: File | undefined, slot: 'logo' | 'hero' | 'gallery') { if (!file || !event) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 8 * 1024 * 1024) { setMessage('Usa JPG, PNG o WebP de hasta 8 MB.'); return }; setUploading(true); setMessage(null); const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${event.organization_id}/${event.id}/${Date.now()}-${safeName}`; const uploaded = await supabase.storage.from('event-landing-assets').upload(path, file, { contentType: file.type, upsert: false }); setUploading(false); if (uploaded.error) { setMessage(uploaded.error.message); return }; const url = supabase.storage.from('event-landing-assets').getPublicUrl(path).data.publicUrl; if (slot === 'logo') set('logo_url', url); if (slot === 'hero') setDraft((current) => ({ ...current, hero_image_url: url, hero_images: [url, ...images(current.hero_images).filter((item) => item !== url)].slice(0, 6) })); if (slot === 'gallery') setDraft((current) => ({ ...current, gallery_images: [...images(current.gallery_images), url].slice(0, 6) })); setMessage('Imagen cargada. Guarda la landing para publicarla.') }
  const subdomain = domain?.slug ? `https://${domain.slug}.eventosfacil.net` : null; const customDomain = domain?.custom_hostname ? `https://${domain.custom_hostname}` : null
  async function copyUrl(url: string) { await navigator.clipboard.writeText(url); setMessage('Enlace copiado.') }
  const gallery = images(draft.gallery_images); const heroImages = images(draft.hero_images)
  return <main className="mx-auto max-w-5xl px-4 py-6 sm:px-7"><header><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Comunicación pública</p><h1 className="mt-1 text-2xl font-bold">Landing del evento</h1><p className="mt-1 text-sm text-zinc-600">Crea una página pública con la identidad, imágenes y llamadas a la acción de este evento.</p></header>{message && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{message}</p>}
    <section className="mt-6 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 font-bold"><Globe2 className="h-5 w-5 text-emerald-700"/>Direcciones públicas</h2><p className="mt-1 text-sm text-zinc-600">Estas direcciones muestran la landing cuando el evento está publicado.</p></div><Link to="/admin/eventos" className="text-sm font-semibold text-emerald-700">Configurar dominio de organización</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{[{label:'Subdominio EventPass',url:subdomain},{label:'Dominio propio',url:customDomain}].map(({label,url}) => <article key={label} className="rounded-xl border border-zinc-200 p-4"><p className="text-xs font-bold uppercase tracking-wide text-zinc-500">{label}</p>{url ? <><a href={url} target="_blank" rel="noreferrer" className="mt-2 block break-all font-semibold text-emerald-700 hover:underline">{url}</a><div className="mt-3 flex gap-2"><button type="button" onClick={() => void copyUrl(url)} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs font-semibold"><Copy className="h-3.5 w-3.5"/>Copiar</button><a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs font-semibold"><ExternalLink className="h-3.5 w-3.5"/>Abrir</a></div></> : <p className="mt-2 text-sm text-zinc-500">No configurado. Usa la configuración de dominio de la organización.</p>}</article>)}</div></section>
    <form onSubmit={save} className="mt-6 space-y-7 rounded-2xl border bg-white p-5"><section><h2 className="font-bold">Plantilla y marca</h2><p className="mt-1 text-sm text-zinc-600">La paleta y el logo del evento prevalecen sobre la marca general de la organización.</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{([['summit','Cumbre','Editorial para congresos y eventos B2B'],['expo','Exposición','Comercial y visual para ferias'],['minimal','Minimal','Convocatoria enfocada en registro']] as const).map(([value,title,detail]) => <label key={value} className={`cursor-pointer rounded-xl border p-4 ${draft.template === value ? 'border-emerald-600 bg-emerald-50' : 'border-zinc-200'}`}><input className="sr-only" type="radio" checked={draft.template === value} onChange={() => set('template', value as LandingTemplate)} /><b className="block">{title}</b><span className="mt-1 block text-xs text-zinc-600">{detail}</span></label>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Color principal<input type="color" value={draft.primary_color || '#047857'} onChange={(e) => set('primary_color', e.target.value)} className="mt-1 block h-10 w-full rounded-lg border p-1"/></label><label className="text-sm font-semibold">Logo del evento<input value={draft.logo_url || ''} onChange={(e) => set('logo_url', e.target.value)} placeholder="https://..." className={input}/></label></div><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><ImagePlus className="h-4 w-4"/><span>{uploading ? 'Cargando...' : 'Subir logo'}</span><input className="sr-only" disabled={uploading} type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void uploadImage(e.target.files?.[0], 'logo')}/></label></section>
      <section><h2 className="font-bold">Hero y carrusel</h2><p className="mt-1 text-sm text-zinc-600">Añade hasta seis imágenes. La primera será la imagen principal y las demás aparecerán como carrusel manual.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{heroImages.map((url, index) => <figure key={url} className="overflow-hidden rounded-xl border"><img src={url} alt="" className="aspect-[4/3] w-full object-cover"/><figcaption className="flex items-center justify-between gap-2 p-2 text-xs"><span>{index === 0 ? 'Imagen principal' : `Imagen ${index + 1}`}</span><button type="button" onClick={() => setDraft((current) => ({ ...current, hero_images: images(current.hero_images).filter((item) => item !== url), hero_image_url: images(current.hero_images).filter((item) => item !== url)[0] || '' }))} aria-label="Eliminar imagen" className="rounded p-1 text-rose-700 hover:bg-rose-50"><Trash2 className="h-4 w-4"/></button></figcaption></figure>)}<label className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed text-sm font-semibold text-zinc-600 hover:border-emerald-600 hover:text-emerald-700"><ImagePlus className="h-6 w-6"/><span className="mt-2">{uploading ? 'Cargando...' : 'Subir imagen'}</span><input className="sr-only" disabled={uploading || heroImages.length >= 6} type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void uploadImage(e.target.files?.[0], 'hero')}/></label></div></section>
      <section><h2 className="font-bold">Contenido principal</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Antetítulo<input value={draft.eyebrow || ''} onChange={(e) => set('eyebrow', e.target.value)} className={input}/></label><label className="text-sm font-semibold">CTA de registro<input value={draft.cta_label || ''} onChange={(e) => set('cta_label', e.target.value)} className={input}/></label><label className="text-sm font-semibold">Lugar<input value={draft.location || ''} onChange={(e) => set('location', e.target.value)} placeholder="Caracas, Venezuela" className={input}/></label><label className="text-sm font-semibold">Texto del brochure<input value={draft.brochure_label || ''} onChange={(e) => set('brochure_label', e.target.value)} className={input}/></label></div><label className="mt-4 block text-sm font-semibold">Titular<input placeholder={event?.name} value={draft.headline || ''} onChange={(e) => set('headline', e.target.value)} className={input}/></label><label className="mt-4 block text-sm font-semibold">Texto de hero<textarea value={draft.subheadline || ''} onChange={(e) => set('subheadline', e.target.value)} className={`${input} min-h-24`}/></label><label className="mt-4 block text-sm font-semibold">Título de presentación<input value={draft.intro_title || ''} onChange={(e) => set('intro_title', e.target.value)} className={input}/></label><label className="mt-4 block text-sm font-semibold">Texto de presentación<textarea value={draft.intro_body || ''} onChange={(e) => set('intro_body', e.target.value)} className={`${input} min-h-24`}/></label><label className="mt-4 block text-sm font-semibold">Enlace externo para brochure o patrocinio<input type="url" value={draft.brochure_url || ''} onChange={(e) => set('brochure_url', e.target.value)} placeholder="https://..." className={input}/></label></section>
      <section><h2 className="font-bold">Galería del evento</h2><p className="mt-1 text-sm text-zinc-600">Estas imágenes se muestran en una galería horizontal adaptada a móviles.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{gallery.map((url, index) => <figure key={url} className="overflow-hidden rounded-xl border"><img src={url} alt="" className="aspect-[4/3] w-full object-cover"/><figcaption className="flex justify-end p-2"><button type="button" onClick={() => set('gallery_images', gallery.filter((item) => item !== url))} aria-label={`Eliminar imagen ${index + 1}`} className="rounded p-1 text-rose-700 hover:bg-rose-50"><Trash2 className="h-4 w-4"/></button></figcaption></figure>)}<label className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed text-sm font-semibold text-zinc-600 hover:border-emerald-600 hover:text-emerald-700"><ImagePlus className="h-6 w-6"/><span className="mt-2">{uploading ? 'Cargando...' : 'Subir galería'}</span><input className="sr-only" disabled={uploading || gallery.length >= 6} type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void uploadImage(e.target.files?.[0], 'gallery')}/></label></div></section>
      <fieldset className="flex flex-wrap gap-4 text-sm font-semibold"><label><input checked={draft.show_agenda !== false} onChange={(e) => set('show_agenda', e.target.checked)} type="checkbox"/> Mostrar agenda</label><label><input checked={draft.show_exhibition !== false} onChange={(e) => set('show_exhibition', e.target.checked)} type="checkbox"/> Mostrar exposición</label><label><input checked={draft.show_interest !== false} onChange={(e) => set('show_interest', e.target.checked)} type="checkbox"/> Mostrar solicitud de información</label></fieldset><button disabled={saving || uploading} className="inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving ? 'Guardando...' : 'Guardar landing'}</button></form>
  </main>
}
