import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Building2 } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Company = { id: string; name: string; contact_name: string | null; contact_email: string | null; contact_phone: string | null }
type Stand = { id: string; label: string; status: string }
type Assignment = { element_id: string; company_id: string }

export default function ExpositoresAdmin() {
  const { eventId } = useParams(); const [companies, setCompanies] = useState<Company[]>([]), [stands, setStands] = useState<Stand[]>([]), [assignments, setAssignments] = useState<Assignment[]>([]), [orgId, setOrgId] = useState<string | null>(null), [name, setName] = useState(''), [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { if (!eventId) return; const { data: event } = await supabase.from('events').select('organization_id').eq('id', eventId).maybeSingle(); if (!event) return; setOrgId(event.organization_id); const { data: map } = await supabase.from('venue_maps').select('id').eq('event_id', eventId).order('created_at', { ascending: false }).limit(1).maybeSingle(); const [firmResult, standResult] = await Promise.all([supabase.from('companies').select('id,name,contact_name,contact_email,contact_phone').eq('organization_id', event.organization_id).eq('kind', 'exhibitor').order('name'), map ? supabase.from('venue_map_elements').select('id,label,status').eq('map_id', map.id).eq('element_type', 'stand').order('label') : Promise.resolve({ data: [], error: null })]); const boothResult = await supabase.from('booth_assignments').select('element_id,company_id').neq('status', 'cancelled'); setCompanies((firmResult.data ?? []) as Company[]); setStands((standResult.data ?? []) as Stand[]); setAssignments(((boothResult.data ?? []) as Assignment[]).filter((item) => (standResult.data ?? []).some((stand) => stand.id === item.element_id))); if (firmResult.error || standResult.error || boothResult.error) setError(firmResult.error?.message ?? standResult.error?.message ?? boothResult.error?.message ?? 'No se pudo cargar.') }, [eventId])
  useEffect(() => { void load() }, [load])
  async function create(event: React.FormEvent) { event.preventDefault(); if (!orgId || !name.trim()) return; const { error: insertError } = await supabase.from('companies').insert({ organization_id: orgId, name: name.trim(), kind: 'exhibitor' }); if (insertError) setError(insertError.message); else { setName(''); await load() } }
  async function assign(companyId: string, standId: string) { const { error: assignmentError } = await supabase.from('booth_assignments').upsert({ element_id: standId, company_id: companyId, status: 'confirmed' }, { onConflict: 'element_id' }); if (!assignmentError) await supabase.from('venue_map_elements').update({ status: 'assigned' }).eq('id', standId); if (assignmentError) setError(assignmentError.message); else await load() }
  const assigned = new Map(assignments.map((item) => [item.company_id, item.element_id]))
  return <div className="min-h-[100dvh] bg-zinc-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center gap-3 px-5 py-4"><Link to={`/admin/stands/${eventId}`}><ArrowLeft className="h-4 w-4" /></Link><Building2 className="h-5 w-5 text-emerald-700" /><span className="font-semibold">Expositores y plano</span></div></header><main className="mx-auto max-w-5xl px-5 py-8"><h1 className="text-2xl font-bold">Asignación comercial</h1><p className="mt-1 text-sm text-zinc-600">Gestiona empresas y espacios del plano sin modificar su diseño.</p>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<form onSubmit={create} className="mt-5 flex gap-2 rounded-xl border bg-white p-4"><input value={name} onChange={(event) => setName(event.target.value)} className="min-w-0 flex-1 rounded-lg border p-2 text-sm" placeholder="Nueva empresa expositora" /><button className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Crear empresa</button></form><div className="mt-6 overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-zinc-50 text-xs text-zinc-600"><tr><th className="p-3">Empresa</th><th className="p-3">Contacto</th><th className="p-3">Espacio</th></tr></thead><tbody>{companies.map((company) => <tr key={company.id} className="border-t"><td className="p-3 font-medium">{company.name}</td><td className="p-3 text-zinc-600">{company.contact_name ?? company.contact_email ?? 'Pendiente'}</td><td className="p-3"><select value={assigned.get(company.id) ?? ''} onChange={(event) => event.target.value && assign(company.id, event.target.value)} className="rounded border p-2 text-sm"><option value="">Sin espacio</option>{stands.filter((stand) => stand.status !== 'assigned' || assigned.get(company.id) === stand.id).map((stand) => <option key={stand.id} value={stand.id}>{stand.label}</option>)}</select></td></tr>)}</tbody></table></div></main></div>
}
