import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { DragDropProvider, useDraggable, useDroppable } from '@dnd-kit/react'
import { ArrowLeft, Store } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Status = 'available' | 'reserved' | 'assigned' | 'blocked'
type FixedType = 'aisle' | 'blank' | 'special'
type Stand = { id: string; label: string; status: Status; x: number; y: number; width: number; height: number }
type Company = { id: string; name: string }
type Assignment = { element_id: string; company_id: string }
type FixedElement = { id: string; label: string; element_type: 'zone' | 'aisle' | 'stage'; x: number; y: number; width: number; height: number; metadata?: { floorplan_kind?: FixedType } | null }
type ElementRect = Pick<Stand, 'x' | 'y' | 'width' | 'height'>

const cellId = (x: number, y: number) => `cell:${x}:${y}`
const classes: Record<Status, string> = { available: 'border-emerald-300 bg-emerald-50 text-emerald-950', reserved: 'border-amber-300 bg-amber-50 text-amber-950', assigned: 'border-sky-400 bg-sky-50 text-sky-950', blocked: 'border-zinc-300 bg-zinc-100 text-zinc-500' }
const fixedTypeOf = (item: FixedElement): FixedType => item.metadata?.floorplan_kind ?? (item.element_type === 'aisle' ? 'aisle' : item.element_type === 'stage' ? 'special' : 'blank')
const databaseTypeFor = (type: FixedType): FixedElement['element_type'] => type === 'aisle' ? 'aisle' : type === 'special' ? 'stage' : 'zone'
const labelFor = (type: FixedType) => type === 'aisle' ? 'Pasillo' : type === 'blank' ? 'Espacio libre' : 'Área especial'

function overlaps(a: ElementRect, b: ElementRect) { return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y }

function GridCell({ x, y }: { x: number; y: number }) {
  const { ref, isDropTarget } = useDroppable({ id: cellId(x, y) })
  return <div ref={ref} className={`border border-zinc-100 ${isDropTarget ? 'bg-emerald-100' : ''}`} style={{ gridColumnStart: x + 1, gridRowStart: y + 1 }} />
}

function DraggableStand({ stand, company, selected, onSelect }: { stand: Stand; company?: Company; selected: boolean; onSelect: () => void }) {
  const { ref, isDragging } = useDraggable({ id: stand.id })
  return <button ref={ref} type="button" onClick={onSelect} className={`z-10 min-h-24 rounded-xl border-2 p-3 text-left transition ${classes[stand.status]} ${selected ? 'ring-2 ring-emerald-700 ring-offset-2' : ''} ${isDragging ? 'opacity-40' : ''}`} style={{ gridColumn: `${stand.x + 1} / span ${stand.width}`, gridRow: `${stand.y + 1} / span ${stand.height}` }}><span className="block text-xs font-bold">{stand.label}</span><span className="mt-2 block text-sm font-semibold leading-tight">{company?.name ?? 'Disponible'}</span></button>
}

function FixedMapElement({ item, selected, onSelect }: { item: FixedElement; selected: boolean; onSelect: () => void }) {
  const kind = fixedTypeOf(item)
  const visual = kind === 'aisle' ? 'border-zinc-400 bg-zinc-100 text-zinc-600' : kind === 'special' ? 'border-violet-400 bg-violet-100 text-violet-950' : 'border-slate-300 bg-slate-100 text-slate-600'
  return <button type="button" onClick={onSelect} className={`z-[1] flex min-h-12 items-center justify-center rounded-lg border border-dashed p-2 text-center text-xs font-semibold transition ${visual} ${selected ? 'ring-2 ring-emerald-700 ring-offset-2' : ''}`} style={{ gridColumn: `${item.x + 1} / span ${item.width}`, gridRow: `${item.y + 1} / span ${item.height}` }}><span>{item.label}</span></button>
}

function FloorplanCanvas({ stands, fixed, companies, assignments, selectedStandId, selectedFixedId, onSelectStand, onSelectFixed, onMove }: { stands: Stand[]; fixed: FixedElement[]; companies: Map<string, Company>; assignments: Map<string, Assignment>; selectedStandId: string | null; selectedFixedId: string | null; onSelectStand: (stand: Stand) => void; onSelectFixed: (item: FixedElement) => void; onMove: (id: string, x: number, y: number) => void }) {
  const columns = Math.max(1, ...stands.map((stand) => stand.x + stand.width), ...fixed.map((item) => item.x + item.width))
  const rows = Math.max(1, ...stands.map((stand) => stand.y + stand.height), ...fixed.map((item) => item.y + item.height))
  return <DragDropProvider onDragEnd={(event) => { if (event.canceled) return; const source = String(event.operation.source?.id ?? ''); const target = String(event.operation.target?.id ?? ''); const match = /^cell:(\d+):(\d+)$/.exec(target); if (match) onMove(source, Number(match[1]), Number(match[2])) }}><div className="overflow-x-auto"><div className="grid min-w-[640px] gap-1 rounded-xl bg-zinc-200 p-1" style={{ gridTemplateColumns: `repeat(${columns}, minmax(96px, 1fr))`, gridTemplateRows: `repeat(${rows}, minmax(84px, 1fr))` }}>{Array.from({ length: columns * rows }, (_, index) => <GridCell key={index} x={index % columns} y={Math.floor(index / columns)} />)}{fixed.map((item) => <FixedMapElement key={item.id} item={item} selected={selectedFixedId === item.id} onSelect={() => onSelectFixed(item)} />)}{stands.map((stand) => <DraggableStand key={stand.id} stand={stand} company={companies.get(assignments.get(stand.id)?.company_id ?? '')} selected={selectedStandId === stand.id} onSelect={() => onSelectStand(stand)} />)}</div></div></DragDropProvider>
}

function FloorplanControls({ onAdd }: { onAdd: (type: FixedType, label: string, x: number, y: number, width: number, height: number) => void }) {
  const [type, setType] = useState<FixedType>('aisle'), [label, setLabel] = useState(labelFor('aisle')), [x, setX] = useState(0), [y, setY] = useState(0), [width, setWidth] = useState(1), [height, setHeight] = useState(1)
  function changeType(next: FixedType) { setType(next); setLabel(labelFor(next)) }
  return <form onSubmit={(event) => { event.preventDefault(); onAdd(type, label.trim() || labelFor(type), x, y, width, height) }} className="mt-6 border-t border-zinc-200 pt-5"><h3 className="font-semibold">Añadir elemento al plano</h3><p className="mt-1 text-xs text-zinc-600">Columna y fila indican la celda inicial. Ancho y alto indican cuántas celdas ocupa. Un pasillo desplaza los stands situados a partir de esa línea.</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-xs font-medium">Tipo<select value={type} onChange={(event) => changeType(event.target.value as FixedType)} className="rounded-lg border p-2 text-sm"><option value="aisle">Pasillo</option><option value="blank">Espacio en blanco</option><option value="special">Área especial</option></select></label><label className="grid gap-1 text-xs font-medium">Nombre<input value={label} onChange={(event) => setLabel(event.target.value)} className="rounded-lg border p-2 text-sm" /></label><label className="grid gap-1 text-xs font-medium">Columna<input type="number" min={0} value={x} onChange={(event) => setX(Number(event.target.value))} className="rounded-lg border p-2 text-sm" /></label><label className="grid gap-1 text-xs font-medium">Fila<input type="number" min={0} value={y} onChange={(event) => setY(Number(event.target.value))} className="rounded-lg border p-2 text-sm" /></label><label className="grid gap-1 text-xs font-medium">Ancho (celdas)<input type="number" min={1} value={width} onChange={(event) => setWidth(Number(event.target.value))} className="rounded-lg border p-2 text-sm" /></label><label className="grid gap-1 text-xs font-medium">Alto (celdas)<input type="number" min={1} value={height} onChange={(event) => setHeight(Number(event.target.value))} className="rounded-lg border p-2 text-sm" /></label></div><button className="mt-3 rounded-lg border border-zinc-300 px-3 py-2 text-sm font-semibold">Añadir al plano</button></form>
}

function FixedElementEditor({ item, onSave, onDelete }: { item: FixedElement; onSave: (item: FixedElement, kind: FixedType) => void; onDelete: (item: FixedElement) => void }) {
  const [draft, setDraft] = useState(item); const [kind, setKind] = useState<FixedType>(fixedTypeOf(item))
  useEffect(() => { setDraft(item); setKind(fixedTypeOf(item)) }, [item])
  const field = (key: 'x' | 'y' | 'width' | 'height', label: string, min: number) => <label className="grid gap-1 text-xs font-medium">{label}<input type="number" min={min} value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: Number(event.target.value) })} className="rounded-lg border p-2 text-sm" /></label>
  return <><h2 className="font-semibold">{item.label}</h2><p className="mt-1 text-xs text-zinc-600">Seleccionado en el plano. Los stands no pueden ocupar estas celdas.</p><div className="mt-4 grid gap-3"><label className="grid gap-1 text-sm">Tipo<select value={kind} onChange={(event) => setKind(event.target.value as FixedType)} className="rounded-lg border p-2"><option value="aisle">Pasillo</option><option value="blank">Espacio en blanco</option><option value="special">Área especial</option></select></label><label className="grid gap-1 text-sm">Nombre<input value={draft.label} onChange={(event) => setDraft({ ...draft, label: event.target.value })} className="rounded-lg border p-2" /></label><div className="grid grid-cols-2 gap-3">{field('x', 'Columna', 0)}{field('y', 'Fila', 0)}{field('width', 'Ancho', 1)}{field('height', 'Alto', 1)}</div></div><button type="button" onClick={() => onSave(draft, kind)} className="mt-4 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Guardar cambios</button><button type="button" onClick={() => onDelete(item)} className="mt-3 w-full rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Eliminar elemento</button><p className="mt-2 text-xs text-zinc-500">Al eliminarlo no se moverán automáticamente los stands.</p></>
}

export default function StandsAdmin() {
  const { eventId } = useParams()
  const [orgId, setOrgId] = useState<string | null>(null), [name, setName] = useState(''), [mapId, setMapId] = useState<string | null>(null), [stands, setStands] = useState<Stand[]>([]), [fixed, setFixed] = useState<FixedElement[]>([]), [companies, setCompanies] = useState<Company[]>([]), [assignments, setAssignments] = useState<Assignment[]>([]), [selectedStandId, setSelectedStandId] = useState<string | null>(null), [selectedFixedId, setSelectedFixedId] = useState<string | null>(null), [companyId, setCompanyId] = useState(''), [rows, setRows] = useState(4), [columns, setColumns] = useState(6), [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { if (!eventId) return; const { data: event } = await supabase.from('events').select('name,organization_id').eq('id', eventId).maybeSingle(); if (!event) return; setName(event.name); setOrgId(event.organization_id); const [{ data: maps }, { data: firms }] = await Promise.all([supabase.from('venue_maps').select('id').eq('event_id', eventId).maybeSingle(), supabase.from('companies').select('id,name').eq('organization_id', event.organization_id).order('name')]); setCompanies((firms ?? []) as Company[]); if (!maps) return; setMapId(maps.id); const { data: elements } = await supabase.from('venue_map_elements').select('id,label,status,x,y,width,height,element_type,metadata').eq('map_id', maps.id); const all = elements ?? []; const standRows = all.filter((item) => item.element_type === 'stand') as Stand[]; setStands(standRows); setFixed(all.filter((item) => item.element_type === 'aisle' || item.element_type === 'zone' || item.element_type === 'stage') as FixedElement[]); const { data: boothData } = await supabase.from('booth_assignments').select('element_id,company_id').neq('status', 'cancelled'); setAssignments(((boothData ?? []) as Assignment[]).filter((item) => standRows.some((stand) => stand.id === item.element_id))) }, [eventId])
  useEffect(() => { void load() }, [load])
  const companyMap = useMemo(() => new Map(companies.map((company) => [company.id, company])), [companies]); const assignmentMap = useMemo(() => new Map(assignments.map((assignment) => [assignment.element_id, assignment])), [assignments])
  async function move(id: string, x: number, y: number) { const stand = stands.find((item) => item.id === id); if (!stand) return; const next = { ...stand, x, y }; if (stands.some((item) => item.id !== id && overlaps(next, item)) || fixed.some((item) => overlaps(next, item))) { setError('Esa posición está ocupada. El stand no fue movido.'); return }; const { error: updateError } = await supabase.from('venue_map_elements').update({ x, y }).eq('id', id); if (updateError) setError(updateError.message); else { setError(null); await load() } }
  async function add(type: FixedType, label: string, x: number, y: number, width: number, height: number) { if (!mapId) { setError('Crea primero la cuadrícula de stands.'); return }; if (type !== 'aisle' && stands.some((stand) => overlaps({ x, y, width, height }, stand))) { setError('Ese elemento ocuparía un stand. Crea un pasillo para desplazar la cuadrícula o elige un espacio libre.'); return }; const { error: insertError } = await supabase.from('venue_map_elements').insert({ map_id: mapId, element_type: databaseTypeFor(type), label, x, y, width, height, status: 'blocked', metadata: { floorplan_kind: type } }); if (insertError) { setError(insertError.message); return }; if (type === 'aisle') { const totalColumns = Math.max(1, ...stands.map((stand) => stand.x + stand.width)); const horizontal = width >= totalColumns; const affected = stands.filter((stand) => horizontal ? stand.y >= y : stand.x >= x); const results = await Promise.all(affected.map((stand) => supabase.from('venue_map_elements').update(horizontal ? { y: stand.y + height } : { x: stand.x + width }).eq('id', stand.id))); const moveError = results.find((result) => result.error)?.error; if (moveError) { setError(`Pasillo creado, pero no se pudieron mover los stands: ${moveError.message}`); return } }; setError(null); await load() }
  async function saveFixed(draft: FixedElement, kind: FixedType) { if (!draft.label.trim() || draft.x < 0 || draft.y < 0 || draft.width < 1 || draft.height < 1) { setError('Completa un nombre y dimensiones válidas.'); return }; if (stands.some((stand) => overlaps(draft, stand))) { setError('No se puede guardar: el elemento se superpone con un stand.'); return }; if (fixed.some((item) => item.id !== draft.id && overlaps(draft, item))) { setError('No se puede guardar: el elemento se superpone con otro elemento del plano.'); return }; const { error: updateError } = await supabase.from('venue_map_elements').update({ label: draft.label.trim(), element_type: databaseTypeFor(kind), x: draft.x, y: draft.y, width: draft.width, height: draft.height, metadata: { floorplan_kind: kind } }).eq('id', draft.id); if (updateError) setError(updateError.message); else { setError(null); await load() } }
  async function removeFixed(item: FixedElement) { if (!window.confirm(`¿Eliminar “${item.label}”? Esta acción no mueve los stands.`)) return; const { error: deleteError } = await supabase.from('venue_map_elements').delete().eq('id', item.id); if (deleteError) setError(deleteError.message); else { setSelectedFixedId(null); setError(null); await load() } }
  async function generate() { if (!eventId || !orgId) return; const { data: map, error: mapError } = await supabase.from('venue_maps').insert({ organization_id: orgId, event_id: eventId, name: 'Plano de exposición' }).select('id').single(); if (mapError || !map) { setError(mapError?.message ?? 'No se pudo crear el plano.'); return }; const elements = Array.from({ length: rows * columns }, (_, index) => ({ map_id: map.id, element_type: 'stand', label: `S${index + 1}`, x: index % columns, y: Math.floor(index / columns), width: 1, height: 1, status: 'available' })); const { error: insertError } = await supabase.from('venue_map_elements').insert(elements); if (insertError) setError(insertError.message); else await load() }
  async function assign() { if (!selectedStandId || !companyId) return; const { error: insertError } = await supabase.from('booth_assignments').upsert({ element_id: selectedStandId, company_id: companyId, status: 'confirmed' }, { onConflict: 'element_id' }); if (!insertError) await supabase.from('venue_map_elements').update({ status: 'assigned' }).eq('id', selectedStandId); if (insertError) setError(insertError.message); else { setCompanyId(''); await load() } }
  async function release() { if (!selectedStandId) return; const assignment = assignmentMap.get(selectedStandId); if (assignment) await supabase.from('booth_assignments').delete().eq('element_id', selectedStandId); await supabase.from('venue_map_elements').update({ status: 'available' }).eq('id', selectedStandId); await load() }
  const selectedStand = stands.find((stand) => stand.id === selectedStandId); const selectedFixed = fixed.find((item) => item.id === selectedFixedId)
  const setup = <div className="mt-6 max-w-xl rounded-xl border bg-white p-5"><h2 className="font-semibold">Crear cuadrícula inicial</h2><p className="mt-1 text-sm text-zinc-600">Define la cantidad de stands antes de comenzar a diseñar el plano.</p><div className="mt-4 grid grid-cols-2 gap-3"><label className="grid gap-1 text-sm">Filas<input type="number" min={1} max={30} value={rows} onChange={(event) => setRows(Number(event.target.value))} className="rounded-lg border p-2" /></label><label className="grid gap-1 text-sm">Stands por fila<input type="number" min={1} max={30} value={columns} onChange={(event) => setColumns(Number(event.target.value))} className="rounded-lg border p-2" /></label></div><button onClick={generate} className="mt-4 rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">Crear {rows * columns} stands</button></div>
  return <div className="min-h-[100dvh] bg-zinc-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-5 py-4"><Link to="/admin/eventos"><ArrowLeft className="h-4 w-4" /></Link><Store className="h-5 w-5 text-emerald-700" /><span className="font-semibold">Plano de exposición</span></div></header><main className="mx-auto max-w-7xl px-5 py-8"><h1 className="text-2xl font-bold">{name}</h1><p className="mt-1 text-sm text-zinc-600">Arrastra un stand a una celda libre. Selecciona un pasillo, espacio en blanco o área especial para modificarlo.</p>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{stands.length ? <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_300px]"><section><div className="mb-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-zinc-600"><span><i className="mr-1 inline-block h-3 w-3 rounded border border-zinc-400 bg-zinc-100 align-[-1px]" />Pasillo</span><span><i className="mr-1 inline-block h-3 w-3 rounded border border-slate-300 bg-slate-100 align-[-1px]" />Espacio en blanco</span><span><i className="mr-1 inline-block h-3 w-3 rounded border border-violet-400 bg-violet-100 align-[-1px]" />Área especial</span></div><FloorplanCanvas stands={stands} fixed={fixed} companies={companyMap} assignments={assignmentMap} selectedStandId={selectedStandId} selectedFixedId={selectedFixedId} onSelectStand={(stand) => { setSelectedStandId(stand.id); setSelectedFixedId(null); setCompanyId(assignmentMap.get(stand.id)?.company_id ?? '') }} onSelectFixed={(item) => { setSelectedFixedId(item.id); setSelectedStandId(null) }} onMove={move} /><FloorplanControls onAdd={add} /></section><aside className="h-fit rounded-xl border bg-white p-4">{selectedFixed ? <FixedElementEditor key={selectedFixed.id} item={selectedFixed} onSave={saveFixed} onDelete={removeFixed} /> : selectedStand ? <><h2 className="font-semibold">Stand {selectedStand.label}</h2><label className="mt-4 grid gap-1 text-sm">Empresa<select value={companyId} onChange={(event) => setCompanyId(event.target.value)} className="rounded-lg border p-2"><option value="">Seleccionar empresa</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><button onClick={assign} className="mt-3 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Guardar asignación</button><button onClick={release} className="ml-2 mt-3 rounded-lg border px-3 py-2 text-sm">Liberar</button></> : <p className="text-sm text-zinc-600">Selecciona un stand para asignar una empresa o un elemento fijo para editarlo.</p>}</aside></div> : setup}</main></div>
}
