import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Grid2X2, Store } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Stand = { id: string; label: string; status: 'available' | 'reserved' | 'assigned' | 'blocked' }
const cls: Record<Stand['status'], string> = { available: 'border-emerald-300 bg-emerald-50 text-emerald-700', reserved: 'border-amber-300 bg-amber-50 text-amber-700', assigned: 'border-zinc-300 bg-zinc-200 text-zinc-500', blocked: 'border-red-300 bg-red-50 text-red-700' }

export default function StandsAdmin() {
  const { eventId } = useParams(); const [name, setName] = useState(''), [org, setOrg] = useState<string | null>(null), [mapId, setMapId] = useState<string | null>(null), [stands, setStands] = useState<Stand[]>([]), [rows, setRows] = useState(4), [cols, setCols] = useState(6), [error, setError] = useState<string | null>(null), [busy, setBusy] = useState(false)
  const load = useCallback(async () => { if (!eventId) return; const { data: m } = await supabase.from('venue_maps').select('id').eq('event_id', eventId).limit(1).maybeSingle(); setMapId(m?.id ?? null); if (m?.id) { const { data, error } = await supabase.from('venue_map_elements').select('id,label,status').eq('map_id', m.id).eq('element_type','stand').order('label'); if (error) setError(error.message); else setStands((data ?? []) as Stand[]) } }, [eventId])
  useEffect(() => { if (!eventId) return; supabase.from('events').select('name,organization_id').eq('id',eventId).maybeSingle().then(({data,error}) => { if(error || !data) setError(error?.message ?? 'Evento no encontrado'); else { setName(data.name); setOrg(data.organization_id); void load() } }) }, [eventId, load])
  async function generate() { if (!eventId || !org || stands.length) return; setBusy(true); setError(null); let id = mapId; if (!id) { const {data,error}=await supabase.from('venue_maps').insert({organization_id:org,event_id:eventId,name:'Plano de exposición'}).select('id').single(); if(error || !data) {setError(error?.message ?? 'No se pudo crear el plano');setBusy(false);return}; id=data.id; setMapId(id) } const elements = Array.from({length:rows*cols},(_,i)=>({map_id:id,element_type:'stand',label:`S${i+1}`,x:i%cols,y:Math.floor(i/cols),width:1,height:1,status:'available'})); const {error}=await supabase.from('venue_map_elements').insert(elements); setBusy(false); if(error)setError(error.message); else void load() }
  async function toggle(s: Stand) { const status=s.status==='available'?'reserved':'available'; const {error}=await supabase.from('venue_map_elements').update({status}).eq('id',s.id); if(error)setError(error.message);else void load() }
  return <div className="min-h-[100dvh] bg-zinc-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-4xl items-center gap-3 px-5 py-4"><Link to="/admin/eventos" className="text-zinc-600"><ArrowLeft className="h-4 w-4"/></Link><Store className="h-4 w-4 text-emerald-600"/><span className="font-semibold">Mapa de stands</span></div></header><main className="mx-auto max-w-4xl px-5 py-8"><h1 className="text-2xl font-bold">{name}</h1><p className="mt-1 text-sm text-zinc-600">Crea el plano comercial y reserva stands; la venta se administra fuera de EventPass.</p>{error&&<p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!stands.length?<section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="font-semibold">Generar cuadrícula de stands</h2><div className="mt-4 flex gap-3"><label>Filas<input className="ml-2 w-16 rounded border p-2" type="number" min={1} max={20} value={rows} onChange={e=>setRows(Number(e.target.value))}/></label><label>Stands por fila<input className="ml-2 w-16 rounded border p-2" type="number" min={1} max={30} value={cols} onChange={e=>setCols(Number(e.target.value))}/></label></div><button disabled={busy} onClick={generate} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white"><Grid2X2 className="h-4 w-4"/>{busy?'Generando…':`Generar ${rows*cols} stands`}</button></section>:<section className="mt-6 rounded-2xl border bg-white p-5"><div className="grid grid-cols-3 gap-3 sm:grid-cols-6">{stands.map(s=><button key={s.id} onClick={()=>toggle(s)} disabled={s.status==='assigned'} className={`rounded-lg border p-4 text-sm font-semibold ${cls[s.status]}`}>{s.label}<span className="mt-1 block text-[10px] font-normal">{s.status}</span></button>)}</div></section>}</main></div>
}
